#+TITLE: GNU Emacs Configuration

This org document serves as the configuration of Emacs, tangling babel
code into init.el with =C-c C-v t= (Tangle) and =H-r= (Reload
init.el).

* Early Initialization
:PROPERTIES:
:header-args:emacs-lisp: :tangle ./early-init.el
:END:

This section handles any configurations that should occur before the loading of the primary init.el. Mostly for loading things before packages, such as garbage collection.

#+begin_src emacs-lisp :tangle "./early-init.el" :lexical t
  ;;; early-init.el --- Emacs early configuration file  -*- lexical-binding: t; -*-

  ;;; Commentary: This file serves as a configuration file for Emacs
  ;; during early startup/ This file is generated from Emacs.org, which
  ;; should exist in the same directory.  This file is loaded upon Emacs
  ;; starting, with init.el loading afterwards.  It is recommended to
  ;; make changes to Emacs.org and regenerate this file instead of
  ;; editing directly.

  ;;; Code:

  ;; GC

  (setq gc-cons-threshold (* 50 1000 1000))

  ;; Paths

  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
  (setq user-emacs-directory "~/.cache/emacs")


  ;; UI

  ;; Hides warnings about undefined functions that aren't present at
  ;; compile-time.  Said functions should appear at runtime when the
  ;; relevant package is loaded.
  ;; Also suppresses warnings about files that use dynamic-binding
  ;; instead of lexical-binding. Mostly for old packages.
  (setq native-comp-async-report-warnings-errors nil)
  (setq warning-suppress-types '((files) (lexical-binding)))

  (setq inhibit-splash-screen nil)
  (setq frame-inhibit-implied-resize t)
  (setq visible-bell t) ; Set up the visible bell
  (scroll-bar-mode -1) ; Disable visible scrollbar
  (tool-bar-mode -1) ; Disable the toolbar
  (tooltip-mode -1) ; Disable tooltips
  (set-fringe-mode 10) ; Give some breathing room
  (menu-bar-mode -1) ; Disable the menu bar
  (display-time-mode 1) ; Displays time in the mode-line
  (display-battery-mode 1) ; Displays battery percentage in the mode-line


  (setq package-enable-at-startup nil)
#+end_src

* Main Initialization
:PROPERTIES:
:header-args:emacs-lisp: :tangle ./init.el
:END:

This section contains the majority of configuration and defines what
will go in the init.el.

** Package Management

Since I am using GNU Guix, we will seek to install packages outside of Emacs and in the system configuration itself. Thus we will not be installing packages from any package manager and instead from Guix channels. I am also explicit about the loading of packages, using =:demand= for explicit loading of packages where possible, as =:defer t= is the default for all packages. Other auto-loading key-words are also usable (e.g. :after, :commands, :binds).

#+begin_src emacs-lisp
  ;;; init.el --- Emacs configuration file -*- lexical-binding: t; -*-
  (setq use-package-always-ensure nil)
  (setq use-package-always-defer t)
#+end_src

** Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp
  (use-package no-littering
    :demand
    :custom
    (no-littering-var-directory "~/.cache/emacs/var")
    (no-littering-etc-directory "~/.cache/emacs/etc")
    :config
    ;; Backup files
    (setq backup-directory-alist
  	`((".*" . ,(no-littering-expand-var-file-name "backup/"))))
    ;; Autosave files
    (setq auto-save-file-name-transforms
  	`((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
    ;; Lock files
    (setq lock-file-name-transforms
  	`((".*" ,(no-littering-expand-var-file-name "lock-files/") t))))
#+end_src

** Meta-Packages

Everything in this section is some form of meta-package or utility that alters the configuration of packages, such as configuration utilities.

*** General

[[https://github.com/noctuid/general.el?tab=readme-ov-file#key-features][General]] provides a more convenient way to bind keys, providing wrappers for base behaviors and more.

#+begin_src emacs-lisp
  (use-package general
    :demand)
#+end_src

*** Config Manipulation

Binds to open/reload this configuration.

#+begin_src emacs-lisp
  ;; Opens this config file
  (defun my/open-init-el ()
    "Opens org-literate init.el file."
    (interactive)
    (find-file
     (expand-file-name "Emacs.org" (file-name-directory user-init-file))))
  (keymap-global-set "H-c" #'my/open-init-el)

  ;; Shortcut to reload init.el
  (defun my/reload-init-el ()
    "Loads init.el the same as M-x load-file, reloading Emacs' configuration.
  Note that not all changes may occur immediately and may require Emacs to be restarted."
    (interactive)
    (load-file user-init-file)
    (message "Init file reloaded"))
  (keymap-global-set "H-r" #'my/reload-init-el)
#+end_src

** UI
*** Theme
[[https://github.com/rexim/gruber-darker-theme][Gruber Darker]] is my chosen theme.

#+begin_src emacs-lisp
  ;; Some face attributes are not set with the theme and require manual setting.
  (use-package gruber-darker-theme
    :demand
    :init
    (load-theme 'gruber-darker t)
    :custom-face
    ;; Line Numbers (The Gutter)
    (line-number ((t (:foreground "#52494e" :background "#181818"))))
    (line-number-current-line ((t (:foreground "#ffdd33" :background "#282828" :bold t)))))


  ;; Org modifications
  (use-package gruber-darker-theme
    :demand
    :after org
    :custom-face
    ;; Org Headings
    (org-level-1 ((t (:foreground "#ffdd33" :weight bold :height 1.2))))
    (org-level-2 ((t (:foreground "#96a6c8" :weight bold :height 1.1))))
    (org-level-3 ((t (:foreground "#95a99f" :weight bold))))
    (org-level-4 ((t (:foreground "#cc8c3c"))))
    (org-hide ((t (:foreground "#181818"))))
    (org-indent ((t (:foreground "#181818" :background "#181818"))))

    ;; Org Blocks (Babel/Source Code)
    (org-block ((t (:background "#202020"))))
    ;; This colors the #+begin_src and #+end_src tags so they disappear into the background
    (org-block-begin-line ((t (:foreground "#52494e" :background "#1a1a1a"))))
    (org-block-end-line ((t (:foreground "#52494e" :background "#1a1a1a"))))

    ;; Org Document Title
    (org-document-title ((t (:foreground "#ffdd33" :weight bold :height 1.5)))))
#+end_src
*** Icons

[[https://github.com/rainstormstudio/nerd-icons.el][Nerd Icons]] is a library for using nerd font icons within Emacs, as an alternative to All The Icons.

#+begin_src emacs-lisp
  (use-package nerd-icons
    :demand)
#+end_src

*** Better Modeline
[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is the modeline of DOOM Emacs, but is still available as a separate package. Note that this will use nerd icons.

#+begin_src emacs-lisp
  (use-package doom-modeline
    :demand
    :init (doom-modeline-mode t)
    :custom
    (doom-modeline-height 15)
    (doom-modeline-window-width-limit fill-column)
    (doom-modeline-project-detection 'auto)
    (doom-modeline-buffer-file-name-style 'auto)
    (doom-modeline-icon t)
    (doom-modeline-major-mode-icon t)
    (doom-modeline-major-mode-color-icon t)
    (doom-modeline-buffer-state-icon t )
    (doom-modeline-buffer-modification-icon t )
    (doom-modeline-lsp-icon t)
    (doom-modeline-time-icon t)
    (doom-modeline-time-live-icon t)
    (doom-modeline-unicode-number t)
    (doom-modeline-unicode-fallback nil)
    (doom-modeline-buffer-name t)
    (doom-modeline-highlight-modified-buffer-name nil)
    (doom-modeline-column-zero-based nil)
    (doom-modeline-minor-modes nil)
    (doom-modeline-selection-info t)
    (doom-modeline-enable-word-count nil)
    (doom-modeline-enable-buffer-position t)
    (doom-modeline-buffer-encoding t)
    (doom-modeline-indent-info t)
    (doom-modeline-total-line-number nil)

    ;; VCS Display
    (doom-modeline-vcs-icon t)
    (doom-modeline-vcs-max-length 15)
    (doom-modeline-vcs-display-function #'doom-modeline-vcs-name)
    (doom-modeline-vcs-state-faces-alist
     '((needs-update . (doom-modeline-warning bold))
       (removed . (doom-modeline-urgent bold))
       (conflict . (doom-modeline-urgent bold))
       (unregistered . (doom-modeline-urgent bold))))

    (doom-modeline-check-icon t)
    (doom-modeline-check 'auto)
    (doom-modeline-number-limit 99)
    (doom-modeline-project-name t)
    (doom-modeline-workspace-name t)
    (doom-modeline-persp-name t)
    (doom-modeline-display-default-persp-name nil)
    (doom-modeline-persp-icon t)
    (doom-modeline-lsp t)

    ;; Modal states (i.e. evil, god, overwrite, etc.)
    (doom-modeline-modal t)
    (doom-modeline-modal-icon t)
    (doom-modeline-modal-mordern-icon t)
    
    (doom-modeline-always-show-macros-register t)

    ;; GNUs
    (doom-modeline-gnus t)
    (doom-modeline-gnus-timer 2)
    (doom-modeline-gnus-excluded-groups '("dummy.group"))

    ;;IRC
    (doom-modeline-irc t)
    (doom-modeline-irc-stylize 'identity)

    (doom-modeline-battery nil)
    (doom-modeline-time nil)
    (doom-modeline-display-misc-in-all-mode-lines t)
    (doom-modeline-remote-host t)
    (doom-modeline-buffer-file-name-function #'identity)
    (doom-modeline-buffer-file-truename-function #'identity)
    (doom-modeline-env-version t)

    :config
    (with-eval-after-load 'ghub
      (setq doom-modeline-github t) ;; Requires `ghub' package
      (setq doom-modeline-github-interval (* 30 60)))) ;; minutes * seconds/minute (Only alter highest unit of time. No 30 second minutes!)
#+end_src

*** Volatile Highlights
[[https://github.com/k-talo/volatile-highlights.el][Volatile Highlights]] makes actions like undoing cause the altered text to remain highlighted until the next command, helping visibility.

#+begin_src emacs-lisp
  (use-package volatile-highlights
    :demand
    :custom
    (vhl/animation-style 'pulse)
    (vhl/highlight-zero-width-ranges t)
    :config
    (volatile-highlights-mode 1)
    (setopt vhl/animation-mid-frames 10
  	  vhl/animation-frame-interval 0.05))
#+end_src

*** Highlighted Indenting
[[https://github.com/DarthFennec/highlight-indent-guides][Highlight-indent-guides]] creates vertical bars where indents are to create a more visual indentation scope.

#+begin_src emacs-lisp
  (use-package highlight-indent-guides
    :demand
    :custom
    (highlight-indent-guides-method 'character)
    (highlight-indent-guides-responsive 'stack)
    :hook (prog-mode . highlight-indent-guides-mode))
#+end_src

*** Minibuffer
**** Vertico

[[https://github.com/minad/vertico][Vertico]] is a minimal vertical minibuffer UI, performing similarly to Ivy and Helm, but with a more native Emacs design and interface.

#+begin_src emacs-lisp

  (use-package vertico    
    :demand
    :init
    (vertico-mode)
    :custom
    ;; Support opening new minibuffers from inside existing minibuffers
    (enable-recursive-minibuffers t)
    ;; Do not allow the cursor in the minibuffer prompt
    (minibuffer-prompt-properties
     '(read-only t cursor-intangible t face minibuffer-prompt)))

  ;; Hide commands in M-x which do not work in the current mode.  Vertico
  ;; commands are hidden in normal buffers. This setting is useful beyond
  ;; Vertico.
  (setq read-extended-command-predicate #'command-completion-default-include-p)

  ;; Persistant history over different Emacs sessions
  (use-package savehist
    :demand
    :init
    (savehist-mode)
    :custom
    (savehist-additional-variables '(search-ring regexp-search-ring kill-ring register-alist)))



#+end_src

**** Orderless

[[https://github.com/oantolin/orderless][Orderless]] provides an order-less completion style.

#+begin_src emacs-lisp

  (use-package orderless
    :demand
    :custom
    ;; Configure a custom style dispatcher (see the Consult wiki)
    ;; (orderless-style-dispatchers '(+orderless-consult-dispatch orderless-affix-dispatch))
    ;; (orderless-component-separator #'orderless-escapable-split-on-space)
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles partial-completion))))
    (completion-category-defaults nil) ;; Disable defaults, use our settings
    (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring

#+end_src

**** Marginalia

[[https://github.com/minad/marginalia][Marginalia]] adds to mini-buffer completions in annotations, providing additional context.

#+begin_src emacs-lisp

  (use-package marginalia    
    :demand
    :init
    (marginalia-mode)
    :bind
    (:map minibuffer-local-map
  	("M-A" . marginalia-cycle)))

#+end_src

*** Navigation
**** Window Manager

Emacs has built-in tiling window management, allowing for very efficient and keyboard driven navigation.

[[https://github.com/emacs-exwm/exwm][EXWM]] is the Emacs window manager for Xorg. This is my replacement for tiling window managers/compositors like Sway/i3, Hyprland, and Niri. By having Emacs supersede the window compositor essentially, Emacs remains the source of configuration for my desktop, allowing for a much more hack-able system.

#+begin_src emacs-lisp
  (use-package exwm-edit
    :demand
    :config
    ;; Edit text in an *exwm-edit* buffer
    (add-to-list 'exwm-input-global-keys '([?\C-c ?\'] . exwm-edit--compose))
    (add-to-list 'exwm-input-global-keys '([?\C-c ?\'] . exwm-edit--compose)))

  (use-package exwm
    :demand
    :custom
    (exwm-replace t)
    :config
    (exwm-systemtray-mode 1)
    (add-hook 'exwm-update-class-hook
    	    (lambda () (exwm-workspace-rename-buffer (concat "X:" exwm-class-name))))
    (exwm-enable))

  (use-package desktop-environment
    :demand
    :config
    (desktop-environment-mode))

  ;; (use-package exwm-firefox-core
  ;;   :after exwm
  ;;   :demand)

  ;; (use-package exwm-firefox
  ;;   :after exwm
  ;;   :demand
  ;;   :config
  ;; (exwm-firefox-mode))

  (use-package exwm-mff
    :after exwm
    :demand
    :bind
    ("s-c" . exwm-mff-warp-to-selected)
    :config
    (exwm-mff-mode 1))

  (use-package exwm-modeline
    :after exwm
    :config
    (exwm-modeline-mode 1))

  (use-package exwm-ss
    :after exwm
    :init
    (exwm-ss-mode 1))
#+end_src

******* Buffer/Window/Tab/Frame Control

#+begin_src emacs-lisp
  (general-define-key
   "s-<left>" #'windmove-left
   "s-<right>" #'windmove-right
   "s-<up>" #'windmove-up
   "s-<down>" #'windmove-down
   "s-j" #'windmove-left
   "s-k" #'windmove-down
   "s-l" #'windmove-up
   "s-;" #'windmove-right

   "s-t 0" #'tab-close
   "s-t 1" #'tab-close-other
   "s-t 2" #'tab-new
   "s-t t" #'other-tab-prefix
   "s-t f" #'find-file-other-tab
   "s-t d" #'dired-other-tab
   "s-t s-o" #'tab-next
   "s-t u" #'tab-undo

   "s-0" #'delete-window
   "s-1" #'delete-other-windows
   "s-2" #'split-window-below
   "s-3" #'split-window-right
   "s-4 4" #'other-window-prefix
   "s-4 f" #'find-file-other-window
   "s-4 c" #'clone-indirect-buffer-other-window)
#+end_src                    

******* Ace-Window

[[https://github.com/abo-abo/ace-window][Ace-window]] allows for fast window selection in the same vein as Avy does with text (and even has the same author!)

#+begin_src emacs-lisp
  (use-package ace-window
    :demand
    :init
    (defvar-keymap my/window-prefix-map
      :doc "Keymap for various window-prefix maps"
      :suppress 'nodigits
      "o" #'ace-window-prefix
      "0" #'ace-window-prefix
      "1" #'same-window-prefix
      "2" #'split-window-vertically
      "3" #'split-window-horizontally
      "4" #'other-window-prefix
      "5" #'other-frame-prefix
      "6" #'other-tab-prefix
      "t" #'other-tab-prefix)
    :bind
    ("s-o" . ace-window))

  (defun ace-window-prefix ()
    "Use `ace-window' to display the buffer of the next command.
      The next buffer is the buffer displayed by the next command invoked
      immediately after this command (ignoring reading from the minibuffer).
      Creates a new window before displaying the buffer.
      When `switch-to-buffer-obey-display-actions' is non-nil,
      `switch-to-buffer' commands are also supported."
    (interactive)
    (display-buffer-override-next-command
     (lambda (buffer _)
       (let (window type)
         (setq
          window (aw-select (propertize " ACE" 'face 'mode-line-highlight))
          type 'reuse)
         (cons window type)))
     nil "[ace-window]")
    (message "Use `ace-window' to display next command buffer..."))
#+end_src

**** Consult

[[https://github.com/minad/consult][Consult]] provides search and navigation commands like Counsel does with Ivy, but using the Emacs built in completion system.

#+begin_src emacs-lisp
  (use-package consult
    :demand
    :bind (;; C-c bindings in `mode-specific-map'
           ("C-c M-x" . consult-mode-command)
           ("C-c h" . consult-history)
           ("C-c k" . consult-kmacro)
           ("C-c m" . consult-man)
           ("C-c i" . consult-info)
           ([remap Info-search] . consult-info)
           ;; C-x bindings in `ctl-x-map'
           ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
           ("s-b" . consult-buffer)                ;; orig. switch-to-buffer
           ("s-4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
           ("s-5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
           ("s-t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
           ("s-r b" . consult-bookmark)            ;; orig. bookmark-jump
           ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
           ;; Custom M-# bindings for fast register access
           ("M-#" . consult-register-load)
           ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
           ("C-M-#" . consult-register)
           ;; Other custom bindings
           ("M-y" . consult-yank-pop)                ;; orig. yank-pop
  	 ("M-R" . consult-recent-file)		   ;; Alternative to recentf
           ;; M-g bindings in `goto-map'
           ;; ("M-g e" . consult-compile-error)
           ;; ("M-g r" . consult-grep-match)
           ;; ("M-g f" . consult-flycheck)               ;; Alternative: consult-flymake
           ;; ("M-g g" . consult-goto-line)             ;; orig. goto-line
           ;; ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
  	 ;; ("M-g o" . consult-org-heading)               ;; Alternative: consult-outline
           ;; ("M-g m" . consult-mark)
           ;; ("M-g k" . consult-global-mark)
           ;; ("M-g i" . consult-imenu)
           ;; ("M-g I" . consult-imenu-multi)
           ;; M-s bindings in `search-map'
  	 ("M-s d" . consult-fd)                  ;; Alternative: consult-find
           ("M-s c" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . consult-ripgrep)
           ("M-s s" . consult-line)		;; Swapping with isearch
  	 ("M-s l" . isearch-forward)
           ("M-s L" . consult-line-multi)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)
           ;; Isearch integration
           ("M-s e" . consult-isearch-history)
           :map isearch-mode-map
           ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
           ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
           ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
           ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
           ;; Minibuffer history
           :map minibuffer-local-map
           ("M-s" . consult-history)                 ;; orig. next-matching-history-element
           ("M-r" . consult-history))                ;; orig. previous-matching-history-element

    ;; The :init configuration is always executed (Not lazy)
    :init

    ;; Tweak the register preview for `consult-register-load',
    ;; `consult-register-store' and the built-in commands.  This improves the
    ;; register formatting, adds thin separator lines, register sorting and hides
    ;; the window mode line.
    (advice-add #'register-preview :override #'consult-register-window)
    (setq register-preview-delay 0.5)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref)
    (setq xref-show-definitions-function #'consult-xref)

    ;; Configure other variables and modes in the :config section,
    ;; after lazily loading the package.
    :config

    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    ;; (setq consult-preview-key 'any)
    ;; (setq consult-preview-key "M-.")
    ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    (consult-customize
     consult-theme :preview-key '(:debounce 0.2 any)
     consult-ripgrep consult-git-grep consult-grep consult-man
     consult-bookmark consult-recent-file consult-xref
     consult-source-bookmark consult-source-file-register
     consult-source-recent-file consult-source-project-recent-file
     ;; :preview-key "M-."
     :preview-key '(:debounce 0.4 any))

    ;; Optionally configure the narrowing key.
    ;; Both < and C-+ work reasonably well.
    (setq consult-narrow-key "<")) ;; "C-+"

  ;; Optionally make narrowing help available in the minibuffer.
  ;; You may want to use `embark-prefix-help-command' or which-key instead.
  ;; (keymap-set consult-narrow-map (concat consult-narrow-key " ?") #'consult-narrow-help)
#+end_src

***** Consult-dir

[[https://github.com/karthink/consult-dir][Consult-dir]] allows you to easily insert directory paths into the minibuffer prompt in Emacs.

When using the minibuffer, you can switch - with completion and filtering provided by your completion setup - to any directory you’ve visited recently, or to a project, a bookmarked directory or even a remote host via tramp. The minibuffer prompt will be replaced with the directory you choose.

#+begin_src emacs-lisp
  (use-package consult-dir
    :after consult)
#+end_src

***** Consult-notes

[[https://github.com/mclear-tools/consult-notes/][Consult-notes]]  a package for easily selecting notes via consult. It’s most basic use is to integrate directories of files (notes) and to provide easy narrowing via  consult. But notes can be in principle added from any source that can be integrated with consult.

consult-notes can be used with any directory (or directories) of note files. It easily integrates with note systems like zk, denote, or org-roam. Additionally, it may also search org headings in a set of specified files.

Consult-notes also provides annotations on note candidates in the minibuffer (defaults are: directory, file size, last-modified time; denote integration substitutes keyword for directory; org-roam integration includes tags and number of backlinks, and org-heading integration provides the file name). Consult-notes may be configured to act on selected candidates via embark.

#+begin_src emacs-lisp
  (use-package consult-notes
    :after consult
    :commands (consult-notes
               consult-notes-search-in-all-notes
               ;; if using org-roam 
               consult-notes-org-roam-find-node
               consult-notes-org-roam-find-node-relation)
    :config
    (setq consult-notes-file-dir-sources '(("Roam"  ?n  "~/Documents/zettelkasten/"))) ;; Set notes dir(s), see below
    ;; Set org-roam integration, denote integration, or org-heading integration e.g.:
    (setq consult-notes-org-headings-files '("~/path/to/file1.org"
                                             "~/path/to/file2.org"))
    (consult-notes-org-headings-mode)
    (consult-notes-org-roam-mode))
#+end_src

**** Embark

[[https://github.com/oantolin/embark][Embark]] provides mini-buffer actions and a context menu, making it easy to choose a command based on what is near the point with  =embark-act= with =C-.=, like a right-click context menu. Running =embark-dwim= with =C-;= runs the default action instead.

#+begin_src emacs-lisp
  (defun sudo-find-file (file)
    "Open FILE as root."
    (interactive "FOpen file as root: ")
    (when (file-writable-p file)
      (user-error "File is user writeable, aborting sudo"))
    (find-file (if (file-remote-p file)
  		 (concat "/" (file-remote-p file 'method) ":"
  			 (file-remote-p file 'user) "@" (file-remote-p file 'host)
  			 "|sudo:root@"
  			 (file-remote-p file 'host) ":" (file-remote-p file 'localname))
                 (concat "/sudo:root@localhost:" file))))

  (use-package embark      
    :demand
    :bind
    (("C-."   . embark-act)
     ("C-;"   . embark-dwim)
     ("C-h B" . embark-bindings)
     :map embark-file-map
     ("S" . sudo-find-file))
    :init
    (setq prefix-help-command #'embark-prefix-help-command)
    (add-hook 'context-menu-functions #'embark-context-menu 100)
    (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
    (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)
    :config
    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
  	       '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
  		 nil
  		 (window-parameters (mode-line-format . none)))))

  (use-package embark-consult
    :after (consult embark))


  ;; Look up the key in `my/window-prefix-map' and call that function first.
  ;; Then run the default embark action.
  (cl-defun my/embark--call-prefix-action (&rest rest &key run type &allow-other-keys)
    (when-let ((cmd (keymap-lookup
                     my/window-prefix-map
                     (key-description (this-command-keys-vector)))))
      (funcall cmd))
    (funcall run :action (embark--default-action type) :type type rest))

  ;; Dummy function, will be overridden by running `embark-around-action-hooks'
  (defun my/embark-set-window () (interactive))

  ;; When running the dummy function, call the prefix action from above
  (setf (alist-get 'my/embark-set-window embark-around-action-hooks)
        '(my/embark--call-prefix-action))

  (setf (alist-get 'buffer embark-default-action-overrides) #'pop-to-buffer-same-window
        (alist-get 'file embark-default-action-overrides) #'find-file
        (alist-get 'bookmark embark-default-action-overrides) #'bookmark-jump
        (alist-get 'library embark-default-action-overrides) #'find-library)

  (map-keymap (lambda (key cmd)
                (keymap-set embark-general-map (key-description (make-vector 1 key))
                            #'my/embark-set-window))
              my/window-prefix-map)
#+end_src

*** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful built-in UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp
  (use-package which-key
    :demand
    :custom
    (which-key-idle-delay 1.5)
    :config
    (which-key-mode))
#+end_src

*** Transient
Transient is by the creators of Magit, providing a menu-based hierarchical input interface. It is mostly used as a dependency in other packages.

#+begin_src emacs-lisp
  (use-package transient
    :demand)
#+end_src

*** Olivetti

[[https://github.com/rnkn/olivetti][Olivetti]] allows for margin resizing in windows, which suits info and markdown pages well as it allows them to center themselves in a window. Especially useful for wide monitors.

#+begin_src emacs-lisp
  (use-package olivetti
    :demand)
#+end_src

*** Helpful Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp
  (use-package helpful
    :demand
    :commands
    (helpful-callable
     helpful-variable
     helpful-command
     helpful-key)
    :bind
    ([remap describe-function] . helpful-callable)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . helpful-variable)
    ([remap describe-key] . helpful-key)
    :custom
    (help-window-select t))
#+end_src

** System Management

Emacs is a very powerful editor and has capabilities far exceeding what a mere text-editor can normally achieve. Using Emacs' hackability along with its extensive package ecosystem as well as GNU Guix's integration with Emacs, a sort of "Emacs Operating System" is able to be hacked together. Many terminal and standalone applications and programs are mostly if not entirely supplanted by Emacs.

Some things are left as external processes for either superior capabilities outside of what Emacs can provide (e.g. web-browsing beyond HTML), or for speed due to Emacs' single-threaded nature.

*** Proced

Proced is Emacs' process editor, replacing the biggest use cases of ps and top, as well as being able to supplant kill. Essentially Proced is like task manager for Windows.

#+begin_src emacs-lisp
  (use-package proced
    :bind
    ("s-s p" . proced)
    :custom
    (display-buffer-alist
     '(("\\*proced\\*"
        (display-buffer-same-window))))
    :config
    (add-hook proced-mode-hook #'proced-toggle-auto-update))
#+end_src

*** IBuffer

IBuffer is Emacs' dedicated mode for editing and interacting with buffers. If in a Emacs driven desktop (e.g. EXWM, EWM, etc.), this serves as a way to handle processes that take up their own buffer.

#+begin_src emacs-lisp
  (use-package ibuffer
    :bind
    ("s-s i" . ibuffer-jump))
#+end_src

*** File Management
**** Recentf

Recentf creates a list of recently visited files that are quickly accessible.

#+begin_src emacs-lisp
  (use-package recentf
    :demand
    :init
    (recentf-mode)
    :custom
    (recentf-max-saved-items 100)
    (recentf-exclude '("/tmp/" "/ssh:" "/terpri/" "\\.git/.*" ".*-autoloads\\.el\\'"))
    :config
    ;; excluding no-littering directories from recentf
    (with-eval-after-load 'no-littering
      (add-to-list 'recentf-exclude
  		 (recentf-expand-file-name no-littering-var-directory))
      (add-to-list 'recentf-exclude
  		 (recentf-expand-file-name no-littering-etc-directory))))
#+end_src

**** Bookmarks

#+begin_src emacs-lisp
  (use-package bookmark
    :demand
    :custom
    (bookmark-save-flag 1) ;; ensures bookmarks are saved on any modification and session end
    :hook
    (bookmark-bmenu-mode-hook . hl-line-mode))
#+end_src

**** Dired

Dired is a built-in file manager for Emacs that works like an interactive =ls -l= command, allowing great power for interacting with file systems.

#+begin_src emacs-lisp
  (use-package dired
    :demand
    :bind
    ("C-x C-j" . dired-jump)
    :custom
    (dired-listing-switches "-l --almost-all --human-readable --group-directories-first --no-group")
    (dired-dwim-target 'dired-dwim-target-recent)
    (dired-recursive-deletes 'top)
    (dired-recursive-copies 'always)
    :config
    (put 'dired-find-alternate-file 'disabled nil)
    :hook
    (dired-mode . hl-line-mode))

  (setq trash-directory "~/.local/share/Trash")
  (setq delete-by-moving-to-trash t)
#+end_src

**** Dirvish

[[https://github.com/alexluigit/dirvish][Dirvish]] is a modern and sleek Dired interface. Features include peeking, pane previews, images, etc.

#+begin_src emacs-lisp
  (use-package dirvish
    :custom
    (dirvish-side-follow-mode t)
    (dirvish-peek-mode t)
    (dirvish-quick-access-entries
     '(("h" "~/"                          "Home")
       ("d" "~/Downloads/"                "Downloads")
       ("m" "/mnt/"                       "Drives")
       ("e" "/sudo:root@localhost:/etc/"  "Modify program settings")
       ("t" "~/.local/share/Trash/files/" "TrashCan")))
    (dirvish-mode-line-format
      	'(:left (file-time " " file-size symlink) :right (omit yank index printable)))
    (dirvish-attributes
      	'(vc-state subtree-state nerd-icons collapse subgroup-name git-mgs file-time file-size))
    (dirvish-side-attributes
          '(vc-state nerd-icons collapse file-size))
    (dirvish-large-directory-threshold 20000)
    :config
    (dirvish-override-dired-mode)
    :bind
    (("C-x C-d" . #'dirvish)
     ("M-0" . #'dirvish-side)
     :map dirvish-mode-map
     (";"   . dired-up-directory)        ; So you can adjust `dired' bindings here
     ("?"   . dirvish-dispatch)          ; [?] a helpful cheatsheet
     ("a"   . dirvish-setup-menu)        ; [a]ttributes settings:`t' toggles mtime, `f' toggles fullframe, etc.
     ("f"   . dirvish-file-info-menu)    ; [f]ile info
     ("o"   . dirvish-quick-access)      ; [o]pen `dirvish-quick-access-entries'
     ("s"   . dirvish-quicksort)         ; [s]ort flie list
     ("r"   . dirvish-history-jump)      ; [r]ecent visited
     ("l"   . dirvish-ls-switches-menu)  ; [l]s command flags
     ("v"   . dirvish-vc-menu)           ; [v]ersion control commands
     ("*"   . dirvish-mark-menu)
     ("y"   . dirvish-yank-menu)
     ("N"   . dirvish-narrow)
     ("TAB" . dirvish-subtree-toggle)
     ("M-f" . dirvish-history-go-forward)
     ("M-b" . dirvish-history-go-backward)
     ("M-e" . dirvish-emerge-menu)
     ("h"   . dirvish-history-last)
     ("H"   . dirvish-history-jump)
     ("M-t" . dirvish-layout-toggle)))
#+end_src

*** Terminal
**** Compilation

Emacs comes with a built-in compilation feature, allowing a command that will compile to be run. It defaults to "make -k" but can be changed to any relevant command for compiling, like "zig build" for example. The previous compile command can be re-run with the recompile command as well, or refreshing the compilation buffer also recompiles as well if that is preferred. There is also a command to compile a project as well, allowing you to compile anywhere. There also exists a minor mode for shell mode that allows compilation mode inside it.

#+begin_src emacs-lisp
  (add-hook 'shell-mode-hook 'compilation-shell-minor-mode)
#+end_src

**** vterm

[[https://github.com/akermu/emacs-libvterm/][vterm]] is an improved terminal emulator package which uses a compiled native module to interact with the underlying terminal applications.  This enables it to be much faster than =term-mode= and to also provide a more complete terminal emulation experience.

#+begin_src emacs-lisp
  (use-package vterm
    :commands vterm
    :bind
    ("C-c M-v" . vterm)
    ("C-c S-M-v" . vterm-other-window))
#+end_src

**** Eshell

[[https://www.gnu.org/software/emacs/manual/html_mono/eshell.html#Contributors-to-Eshell][Eshell]] is Emacs' own shell implementation written in Emacs Lisp. It allows you to call Emacs Lisp functions directly from the shell and set up aliases. Eshell is also an Emacs Lisp REPL which allows you to evaluate full expressions at the shell.

For more thoughts on Eshell, check out these articles by Pierre Neidhardt:
- https://ambrevar.xyz/emacs-eshell/index.html
- https://ambrevar.xyz/emacs-eshell-versus-shell/index.html

#+begin_src emacs-lisp
  (defun configure-eshell ()
    ;; Save command history when commands are entered
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    (setq eshell-history-size         10000)
    (setq eshell-buffer-maximum-lines 10000)
    (setq eshell-hist-ignoredups t)
    (setq eshell-scroll-to-bottom-on-input t))

  (use-package eshell
    :bind
    ("C-c M-e" . eshell)
    :config
    (eshell-git-prompt-use-theme 'powerline)
    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t)
      (setq eshell-visual-commands '("htop" "zsh" "vim")))
    :hook (eshell-first-time-mode . configure-eshell))

  (use-package eshell-git-prompt
    :after eshell)
#+end_src

*** Info/Man

Info and Man pages are the main ways of reading documentation of the system and programs. Here are some configurations to aid in the UX of them.

#+begin_src emacs-lisp
  (use-package info
    :demand
    :hook
    (Info-mode . olivetti-mode)
    (Info-mode . (lambda ()
                   (variable-pitch-mode 1)
                   (setq line-spacing 0.2))))

  (use-package man
    :demand)
#+end_src

*** PDF-Tools

[[https://github.com/vedang/pdf-tools][pdf-tools]] Is a superior PDF viewing mode for Emacs.

#+begin_src emacs-lisp
  (use-package pdf-tools
    :demand
    :custom
    (pdf-annot-activate-created-annotations t)
    (pdf-view-resize-factor 1.1)
    (pdf-view-display-size 'fit-page)
    :bind (:map pdf-view-mode-map
       	      ("C-s" . isearch-forward))
    :hook
    ((pdf-view-mode) . (lambda () (cua-mode 0)))
    :config
    (pdf-tools-install)
    (add-to-list 'auto-mode-alist '("\\.pdf\\'" . pdf-view-mode)))
#+end_src

** Text Editing
*** Org Mode

Org-mode is Emacs' superior markdown mode and one of its killer features. It has a wide ecosystem of extensions and incredible capabilities, including allowing literate programming like seen in this very configuration.

**** Org-Mode
***** Better Font Faces

The =org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (mono-space) fonts for code blocks and tables so that they display correctly. Cantarell is the used font, so ensure it is installed on the system.

#+begin_src emacs-lisp
  (defun org-font-setup ()
    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))
#+end_src

***** Config

This section contains the basic configuration for =org-mode=, setting up proper modes and formatting.
  
#+begin_src emacs-lisp
  (use-package org
    :demand
    :init
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
        			  '(("^ *\\([-]\\) "
        			     (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
    :mode ("\\.org\\'" . org-mode)
    :custom
    (org-ellipsis " ▾")
    (org-fontify-whole-heading-line t)
    (org-capture-templates
     '(("p" "Protocol" entry (file+headline "~/org/inbox.org" "Inbox")
        "* %^{Title}\nSource: %u, %c\n\n%i")
       ("L" "Protocol Link" entry (file+headline "~/org/inbox.org" "Links")
        "* %? [[%:link][%:description]] \nCaptured On: %U")))
    :bind
    (("C-c a" . #'org-agenda)
     (:map org-mode-map
        	 ("C-c s h" . #'org-insert-heading)
        	 ("C-c s s" . #'org-insert-subheading)))
    :config
    (require 'org-protocol)
    (org-font-setup)
    :hook
    ((org-mode . org-indent-mode)
     (org-mode . variable-pitch-mode)
     (org-mode . visual-line-mode)))
#+end_src

***** Nicer Heading Bullets
[[https://github.com/integral-dw/org-superstar-mode][org-superstar-mode]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.

#+begin_src emacs-lisp
  (use-package org-superstar
    :after org
    :custom
    (org-superstar-headline-bullets-list '("◉" "○" "●" "○" "●" "○" "●"))
    ;; Optional: This makes the "leading" stars invisible for a cleaner look
    (org-superstar-remove-leading-stars t)
    :hook
    (org-mode . org-superstar-mode))
#+end_src

**** Org-Babel
***** Languages
****** ob-racket

[[https://github.com/hasu/emacs-ob-racket][Org Babel support for Racket]].

#+begin_src emacs-lisp
  (use-package ob-racket
    :after org
    :config
    (add-hook 'ob-racket-pre-runtime-library-load-hook
  	    #'ob-racket-raco-make-runtime-library))
#+end_src

***** Configuration

To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages/index.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (lisp . t)
       (C . t)
       (css . t)
       (shell . t)
       (eshell . t)
       (gnuplot . t)
       (python . t)
       (latex . t)
       (scheme .t)
       (racket . t)))
    (setq org-confirm-babel-evaluate nil)
    (setq org-startup-with-inline-images t)

    (push '("conf-unix" . conf-unix) org-src-lang-modes))
#+end_src

***** Structure Templates

Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp
  (with-eval-after-load 'org
    ;; This is needed as of Org 9.2
    (require 'org-tempo)
    ;; "c" is set to center. We want to delete this and replace it with "cen" to free "c" for C language blocks.
    (setq org-structure-template-alist (assoc-delete-all "c" org-structure-template-alist))
    (add-to-list 'org-structure-template-alist '("cen" . "center"))

    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("lisp" . "src lisp"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("esh" . "src eshell"))
    (add-to-list 'org-structure-template-alist '("c" . "src C"))
    (add-to-list 'org-structure-template-alist '("cp" . "src C++"))
    (add-to-list 'org-structure-template-alist '("cs" . "src css"))
    (add-to-list 'org-structure-template-alist '("py" . "src python"))
    (add-to-list 'org-structure-template-alist '("gp" . "src gnuplot"))
    (add-to-list 'org-structure-template-alist '("ra" . "src racket"))
    (add-to-list 'org-structure-template-alist '("sc" . "src scheme")))
#+end_src
**** Org-Roam

[[https://www.orgroam.com/][Org-roam]] uses Org-mode with a SQLite to generate a node based note taking system, like Obsidian.md. [[https://www.youtube.com/watch?v=YxgA5z2R08I][This Video by System Crafters]] explains how to utilize Org-roam. I am using mounted google drive with rclone to have my notes be synced across devices.

#+begin_src emacs-lisp
  (defun my/tomorrow-date ()
    "Gets the Y/M/D of tomorrow."
    (let* ((day-in-seconds (* 24 60 60))
  	 (tomorrow-time (time-add (current-time) day-in-seconds)))
      (format-time-string "%Y-%m-%d" tomorrow-time)))

  (use-package org-roam
    :after org
    :init
    (setq org-roam-v2-ack t)
    :custom
    (org-roam-directory (file-truename "~/Documents/zettelkasten/"))
    (org-roam-completion-everywhere t)
    (org-roam-capture-templates
     '(
       ;; F - FLEETING NOTE
       ;; Fast capture for temporary thoughts. 
       ;; Includes a TODO for the "Daily Review" mentioned in the video.
       ("f" "Fleeting" plain
        "%?"
        :if-new (file+head "fleeting/${slug}.org"
                           "#+title: ${title}\n#+filetags: :fleeting:unfiled:\n\n* TODO Review this fleeting thought\nSCHEDULED: <%(my/tomorrow-date)>\nCaptured: %U\n\n%i")
        :immediate-finish t)

       ;; L - LITERATURE GROUP
       ("l" "Literature")
       
       ;; LT - LITERATURE NOTE
       ;; For capturing insights from books and articles.
       ("lt" "Literature/Text" plain "%?"
        :if-new (file+head "literature/${slug}.org"
     			 ":PROPERTIES:\n:ROAM_REFS:\n:END:\n#+title: ${citar-title} (${citar-date})\n#+filetags: :literature:unfiled:\nLATEX_HEADER: \\usepackage{tikz}\n\n* Authors\n${citar-author}\n\n* Abstract\n${citar-abstract}\n\n* Highlights\n%i\n\n")
        :unnarrowed t)
       
       ;; LR - REFERENCE NOTE
       ;; For capturing pure facts. Atomic information to be referenced.
       ("lr" "Literature/Reference" plain
        "%?"
        :if-new (file+head "literature/${slug}.org"
                           ":PROPERTIES:\n:ROAM_REFS:\n:END:\n#+title: ${title}\n#+filetags: :reference:\n#+LATEX_HEADER: \\usepackage{tikz}\n\n* Information\n- %i")
        :unnarrowed t)
       
       ;; LV - VIDEO NOTE
       ;; For capturing insights from videos.
       ("lr" "Literature/Video" plain
        "%?"
        :if-new (file+head "literature/${slug}.org"
     			 "PROPERTIES:\n:ROAM_REFS:\n:END:\n#+title: ${citar-title}\n#+filetags: :literature:unfiled:\n#+LATEX_HEADER: \\usepackage{tikz}\n\n* Authors\n${citar-author}\n\n* Source\n${citar-url}* Abstract\n${citar-abstract}\n\n* Highlights\n- [ ] ")
        :unnarrowed t)
       
       ;; A - ATOMIC NOTE
       ;; The "Golden Unit." One idea, in your own words.
       ;; Includes the "Up" property for the tree-structure hierarchy.
       ("a" "Atomic" plain
        "%?"
        :if-new (file+head "atomic/${slug}.org"
     			 ":PROPERTIES:\n:UP: \n:END:\n#+LATEX_HEADER: \\usepackage{tikz}\n#+title: ${title}\n#+filetags: :atomic:\n\n\n\n* See Also\n\n\n* Original Capture\n\"\"")
        :unnarrowed t)

       ;; P - PROJECT NOTE
       ;; For active outcomes (essays, videos, study goals).
       ("p" "Project" plain
        "%?"
        :if-new (file+head "projects/${slug}.org"
     			 "#+title: ${title}\n#+filetags: :project:active:\n\n* Objective\n%^{Goal}\n\n* Tasks [0/0]\n- [ ] \n\n* Relevant Atomic Notes\n%i")
        :unnarrowed t)
       ))
    :bind (("C-c n l" . org-roam-buffer-toggle)
  	 ("C-c n f" . org-roam-node-find)
  	 ("H-n" . org-roam-node-find)
  	 ("C-c n i" . org-roam-node-insert)
  	 :map org-mode-map
  	 ("C-M-i" . completion-at-point))
    :config
    (org-link-set-parameters "roam" :face '(:foreground "red" :weight bold))
    (my/org-roam-refresh-agenda-list)
    (org-roam-db-autosync-enable))

  (defun my/org-roam-refresh-agenda-list ()
    (interactive)
    (setq org-agenda-files (directory-files-recursively org-roam-directory "\\.org$")))

#+end_src

***** Org-Roam-UI

[[https://github.com/org-roam/org-roam-ui][Org-Roam-UI]] Zettelkasten for Org-Roam, creating a graph like Obsidian.md for Roam nodes. =M-x org-roam-ui-mode RET= mode and starts a web server. URL for web server is [[http://127.0.0.1:35901/]] 

#+begin_src emacs-lisp

  ;; Dependencies for Roam UI are websocket and simple-httpd
  (use-package simple-httpd
    :demand)
  (use-package websocket
    :demand)
  (use-package org-roam-ui
    :after
    (org-roam simple-httpd websocket))

#+end_src

**** Org-Noter

[[https://github.com/org-noter/org-noter][Org-Noter]] allows org files to synchronize and follow linked PDF in an attached window.

#+begin_src emacs-lisp
  (use-package org-noter
    :after org)

  (use-package org-pdftools
    :after (org pdf-tools)
    :hook
    (org-mode . org-pdftools-setup-link))

  (use-package org-noter-pdftools
    :after (org-noter pdf-tools)
    :config
    ;; Add a function to ensure precise note is inserted
    (defun org-noter-pdftools-insert-precise-note (&optional toggle-no-questions)
      (interactive "P")
      (org-noter--with-valid-session
       (let ((org-noter-insert-note-no-questions (if toggle-no-questions
                                                     (not org-noter-insert-note-no-questions)
                                                   org-noter-insert-note-no-questions))
             (org-pdftools-use-isearch-link t)
             (org-pdftools-use-freepointer-annot t))
         (org-noter-insert-note (org-noter--get-precise-info)))))

    ;; fix https://github.com/weirdNox/org-noter/pull/93/commits/f8349ae7575e599f375de1be6be2d0d5de4e6cbf
    (defun org-noter-set-start-location (&optional arg)
      "When opening a session with this document, go to the current location.
  With a prefix ARG, remove start location."
      (interactive "P")
      (org-noter--with-valid-session
       (let ((inhibit-read-only t)
             (ast (org-noter--parse-root))
             (location (org-noter--doc-approx-location (when (called-interactively-p 'any) 'interactive))))
         (with-current-buffer (org-noter--session-notes-buffer session)
           (org-with-wide-buffer
            (goto-char (org-element-property :begin ast))
            (if arg
                (org-entry-delete nil org-noter-property-note-location)
              (org-entry-put nil org-noter-property-note-location
                             (org-noter--pretty-print-location location))))))))
    (with-eval-after-load 'pdf-annot
      (add-hook 'pdf-annot-activate-handler-functions #'org-noter-pdftools-jump-to-note)))
#+end_src

**** Org-Transclusion

[[https://github.com/nobiot/org-transclusion][Org-transclusion]] is a package that allows snippets of org files to be included within other org files without needing to copy and paste, allowing live and asynchronous editing of quoted sections.

#+begin_src emacs-lisp
  (use-package org-transclusion
    :after org
    :config
    (org-transclusion-font-lock-mode 1))
#+end_src

**** Citar

[[https://github.com/emacs-citar/citar][Citar]] is a package that allows easy and powerful management of citations. It integrates well with native Emacs packages and completion frameworks like Ivy and Vertico. It also has good integration with Embark and Org-Roam, allowing for instant transitioning to linked references.

#+begin_src emacs-lisp
  (use-package citar
    :after org-roam
    :custom
    (citar-bibliography (file-truename "~/Documents/zettelkasten/ReferenceMaterials/references.bib"))
    (citar-notes-paths '("~/Documents/zettelkasten/literature/"))
    :hook
    (LaTeX-mode . citar-capf-setup)
    (org-mode . citar-capf-setup)
    :config
    (add-to-list 'citar-org-roam-template-fields '((:citar-abstract . ("abstract"))
  						 (:citar-url . ("url")))))

  (use-package citar-embark
    :after (citar embark)
    :config
    (citar-embark-mode))

  (use-package citar-org-roam
    :after (citar org-roam)
    :custom
    (citar-org-roam-note-title-template "${author} - ${title}")
    (citar-org-roam-capture-template-key "l")
    :bind
    ("C-c n c" . citar-create-note)
    :config
    (citar-org-roam-mode 1))
#+end_src

**** Zotra

Zotero is a bibliographic tool, allowing a citation to be generated by simply clicking the extension button in a browser or by using the Zotero client. [[https://github.com/mpedramfar/zotra][Zotra]] is a translator package for Emacs that can use URLs and search identifiers to fetch bibliographic information directly within Emacs.

#+begin_src emacs-lisp
  (use-package zotra
    :demand
    :custom
    (zotra-backend 'zotra-server)
    (zotra-default-bibliography (file-truename "~/Documents/zettelkasten/ReferenceMaterials/references.bib"))
    (zotra-download-attachment-default-directory (file-truename "~/Documents/zettelkasten/ReferenceMaterials/")))
#+end_src

*** Typesetting
**** LaTeX
LaTeX is the standard way of writing mathematical documents and an excellent way to create documents generally like PDFs. AUCTeX is the Emacs mode for editing LaTeX.

#+begin_src emacs-lisp
  (use-package auctex
    :mode
    ("\\.tex\\'" . latex-mode)
    :custom
    (TeX-auto-save t)
    (TeX-parse-self t)
    (TeX-PDF-mode t)
    (reftex-plug-into-AUCTeX t)
    :hook
    ((LaTeX-mode . LaTeX-math)
     (LaTeX-mode . turn-on-reftex)))
#+end_src
**** BibTeX
BibTeX is a TeX format for bibliographies.

#+begin_src emacs-lisp
  (use-package bibtex
    :demand
    :custom
    (bibtex-dialect 'biblatex)
    (bibtex-align-at-equal-sign t)
    (bibtex-text-indentation 2)
    :hook
    (bibtex-mode . (lambda ()
                     (add-hook 'after-save-hook #'bibtex-reformat nil t))))
#+end_src

*** Syntax Checking

[[https://github.com/flycheck/flycheck][Flycheck]] is a more feature-rich version of the built-in Flymake, providing out-of-the-box syntax highlighting in many languages. [[https://github.com/flycheck/flycheck-pos-tip][Flycheck-pos-tip]] displays errors in a pop-up display when hovering over an error.

#+begin_src emacs-lisp
  (use-package flycheck
    :demand
    :init (global-flycheck-mode +1))

  (use-package flycheck-pos-tip
    :after flycheck
    :config
    (flycheck-pos-tip-mode +1))
#+end_src

*** Spellchecking

Emacs has the native Ispell spellchecking package, which has been superseded by the more modern Flyspell package. However, [[https://github.com/minad/jinx][Jinx]] is an even more modern and more versatile spell-checker which can use several dictionaries like Hunspell and Aspell through the use of Enchant. Requires external enchant package!!

#+begin_src emacs-lisp
  (use-package jinx
    :demand
    :bind
    ("M-$" . jinx-correct-nearest)
    ("C-M-$" . jinx-correct-all)
    :hook
    (text-mode . jinx-mode)
    (prog-mode . jinx-mode)
    (conf-mode . jinx-mode))
#+end_src

*** Completion

[[https://github.com/minad/corfu][Corfu]] enhances in-buffer completion like Company mode does, instead using Emacs built-in completion.

#+begin_src emacs-lisp
  (use-package corfu
    :demand
    :init

    ;; Recommended: Enable Corfu globally.  Recommended since many modes provide
    ;; Capfs and Dabbrev can be used globally (M-/).  See also the customization
    ;; variable `global-corfu-modes' to exclude certain modes.
    (global-corfu-mode)

    ;; Enable optional extension modes:
    (corfu-history-mode)
    (corfu-popupinfo-mode)
    :custom
    (add-hook 'eshell-mode-hook (lambda ()
  				(setq-local corfu-auto nil)
  				(corfu-mode)))
    (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    (corfu-quit-no-match 'separator)
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match 'insert) ;; Configure handling of exact matches
    )

  ;; A few more useful configurations...
  (use-package emacs
    :custom
    ;; TAB cycle if there are only few candidates
    ;; (completion-cycle-threshold 3)

    ;; Enable indentation+completion using the TAB key.
    ;; `completion-at-point' is often bound to M-TAB.
    (tab-always-indent 'complete)

    ;; Emacs 30 and newer: Disable Ispell completion function.
    ;; Try `cape-dict' as an alternative.
    (text-mode-ispell-word-completion nil)

    ;; Hide commands in M-x which do not apply to the current mode.  Corfu
    ;; commands are hidden, since they are not used via M-x. This setting is
    ;; useful beyond Corfu.
    (read-extended-command-predicate #'command-completion-default-include-p))
#+end_src

*** Multiple Cursors

[[https://github.com/magnars/multiple-cursors.el][Multiple cursors]] functions like it does in other editors, allowing multiple lines to be edited with a single string of keys, as if editing one single line.

#+begin_src emacs-lisp
  (use-package multiple-cursors
    :bind
    ("C-S-c C-S-c" . mc/edit-lines))
#+end_src

*** Macros

Emacs macros essentially let you do anything and have it be repeatable. Text editing, window configuration, opening a shell and inserting specific commands then closing it, etc.

#+begin_src emacs-lisp
  (require 'kmacro)
  (defalias 'kmacro-insert-macro 'insert-kbd-macro)
  (keymap-set kmacro-keymap "I" #'kmacro-insert-macro)

  (keymap-global-set "A-r s" #'kmacro-start-macro-or-insert-counter)
  (keymap-global-set "A-r e" #'kmacro-end-or-call-macro)
#+end_src

Because macros are impermanent, they need to be remade each session. However, if a macro is named with =C-x C-k n=,  we can insert an elisp function that mimics the macro. This can be saved and re-used between sessions.

#+begin_src emacs-lisp
  (defun my/insert-macro-into-file (file-path search-word macro-name)
    "Finds SEARCH-WORD in FILE-PATH and inserts the definition of MACRO-NAME after it."
    (if (file-exists-p file-path)
        (with-temp-file file-path
          (insert-file-contents file-path)
          (goto-char (point-min))
          (if (search-forward search-word nil t)
              (progn
                (insert "\n")
                ;; insert-kbd-macro prints into the current (temp) buffer
                (insert-kbd-macro macro-name))
            (message "Search word '%s' not found in %s" search-word file-path)))
      (error "File not found: %s" file-path)))

  (defun my/save-macro (macro-name)
    "Saves a selected macro into the init file after the marker."
    (interactive
     (list (completing-read "Save macro: " obarray
                            (lambda (s) (and (commandp s) (get s 'kmacro)))
                            t)))
    (let ((macro-symbol (intern macro-name)))
      (my/insert-macro-into-file "~/.config/emacs/Emacs.org" "AUTOMACROINSERT\n" macro-symbol)
      (message "Macro '%s' saved to %s" macro-name "~/.config/emacs/Emacs.org")))

  (keymap-global-set "C-x C-k C-i" #'my/save-macro)
#+end_src

**** Custom Macros

Here is a section of my saved macros.

#+begin_src emacs-lisp
  ;; AUTOMACROINSERT

#+end_src

*** Text Navigation

Despite Emacs having great native text navigation and traversal, several packages greatly aid in the speed and efficiency of navigation.
**** Avy

[[https://github.com/abo-abo/avy][Avy]] allows you to navigate the on-screen buffer like a tree, using goto commands to navigate fast, sort of like Vimium hypertext search.

[[https://karthinks.com/software/avy-can-do-anything/][This blog post]] demonstrates the great power available in Avy, allowing you to perform arbitrary actions upon any selection of text without moving the cursor.

#+begin_src emacs-lisp
  (defun avy-action-embark (pt)
    "Dispatches Embark upon an Avy selection."
    (save-excursion
      (goto-char pt)
      (embark-act))
    (select-window
     (cdr (ring-ref avy-ring 0)))
    t)

  (defun avy-action-helpful (pt)
    "Dispatches Helpful upon the symbol selected via Avy."
    (save-excursion
      (goto-char pt)
      (helpful-at-point))
    (select-window
     (cdr (ring-ref avy-ring 0)))
    t)

  (use-package avy
    :demand
    :after org
    :bind
    (("M-g M-g" . avy-goto-line)
     ("M-g g"   . avy-goto-line)
     ("C-:"     . avy-goto-char-timer)
     :map isearch-mode-map
     ("M-j"     . avy-isearch))
    :config
    (setf (alist-get ?. avy-dispatch-alist) 'avy-action-embark)
    (setf (alist-get ?i avy-dispatch-alist) 'avy-action-helpful))
#+end_src

**** ISearch

Isearch is the built-in package for incrementally searching within Emacs. It can make great use of both Avy and Embark for quick searching and dispatching of actions for blazingly fast editing and navigation.

#+begin_src emacs-lisp
  (defun isearch-forward-ace-window (prefix)
    "Function to isearch-forward in ace-window."
    (interactive "P")
    (unless (one-window-p)
      (save-excursion
        (let ((next (if prefix -1 1)))
          (ace-window next)
          (isearch-forward)
          (ace-window (- next))))))

  (defun isearch-backward-ace-window (prefix)
    "Function to isearch-backward in ace-window."
    (interactive "P")
    (unless (one-window-p)
      (save-excursion
        (let ((next (if prefix 1 -1)))
          (ace-window next)
          (isearch-backward)
          (ace-window (- next))))))

  (use-package isearch    
    :demand
    :bind
    ("C-M-s" . isearch-forward-ace-window)
    ("C-M-r" . isearch-backward-ace-window)
    :custom
    (isearch-lazy-count t)
    (isearch-wrap-pause 'no)
    (isearch-repeat-on-direction-change t)
    (search-upper-case t))
#+end_src

**** Expand Region

[[https://github.com/magnars/expand-region.el][Expand Region]] increases the selected region by semantic units. Just keep pressing the key until it selects what you want.

#+begin_src emacs-lisp
  (use-package expand-region
    :demand
    :bind
    ("C-=" . er/expand-region))
#+end_src

*** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :demand
    :hook
    (prog-mode . rainbow-delimiters-mode))
#+end_src

** Development

This section contains configurations and packages that aid in development/programming.

*** Languages
**** LSP with Eglot

[[https://github.com/joaotavora/eglot][Eglot]] is the native Emacs's lsp client. It can be run with [[https://github.com/blahgeek/emacs-lsp-booster][lsp-booster]] to convert JSON data into bytecode, massively speeding up Emacs's interpreter and removing many stutters due to its single-threaded nature. Note that Emacs v30 introduced a JSON parser that decodes faster than bytecode, but has slower I/O. Emacs-lsp-booster offers the option =--disable-bytecode=, which with setting =eglot-booster-io-only=t= will use to get the benefit of I/O buffering with the native JSON parser. Eglot also uses Flymake as its syntax renderer, which can be swapped to Flycheck with another [[https://github.com/flycheck/flycheck-eglot][package]].

#+begin_src emacs-lisp
  (use-package eglot
    :demand
    :custom
    (eglot-autoshutdown t)
    :config
    (add-to-list 'eglot-stay-out-of 'flymake)
    (add-hook 'eglot-managed-mode-hook
              (lambda ()
                (add-hook 'before-save-hook #'eglot-format-buffer nil t)))
    (setq read-process-output-max (* 4 1024 1024)) ;; Increase Process Output Buffer for LSP
    )

  (use-package flycheck-eglot
    :after (flycheck eglot)
    :config
    (global-flycheck-eglot-mode 1))
#+end_src

**** Treesit

Treesitter has compatibility with Emacs as long as Emacs is compiled with it enabled!! [[https://github.com/mickeynp/combobulate][Combobulate]] is a package that handles several languages grammar for Treesit.

#+begin_src emacs-lisp
  (use-package treesit
    :demand
    :mode (("\\.tsx\\'" . tsx-ts-mode))
    :preface
    ;; Optional. Combobulate works in both xxxx-ts-modes and
    ;; non-ts-modes.

    ;; You can remap major modes with `major-mode-remap-alist'. Note
    ;; that this does *not* extend to hooks! Make sure you migrate them
    ;; also
    (dolist (mapping
             '((python-mode . python-ts-mode)
               (typescript-mode . typescript-ts-mode)
               (js2-mode . js-ts-mode)
               (bash-mode . bash-ts-mode)
               (conf-toml-mode . toml-ts-mode)
               (go-mode . go-ts-mode)
               (css-mode . css-ts-mode)
               (json-mode . json-ts-mode)
               (js-json-mode . json-ts-mode)))
      (add-to-list 'major-mode-remap-alist mapping))
    :custom
    (treesit-font-lock-level 4))

  ;; Do not forget to customize Combobulate to your liking:
  ;;
  ;;  M-x customize-group RET combobulate RET
  ;;
  (use-package combobulate
    :custom
    ;; You can customize Combobulate's key prefix here.
    ;; Note that you may have to restart Emacs for this to take effect!
    (combobulate-key-prefix "C-c M-o")
    :hook (prog-mode . combobulate-mode))
#+end_src

**** 

**** Debugging with dape

[[https://github.com/svaante/dape][dape]] is the Debug Adapter Protocol for Emacs, functioning like dap-mode does. Invoking the =M-x dape= command begins a debugging session. Enabling repeat-mode and eldoc-mode is highly recommended.

#+begin_src emacs-lisp
  (use-package dape
    :commands (dape)
    :preface
    ;; By default dape shares the same keybinding prefix as `gud'
    ;; If you do not want to use any prefix, set it to nil.
    (setq dape-key-prefix "\C-x\C-a")

    :hook
    ;; Save breakpoints on quit
    (kill-emacs . dape-breakpoint-save)
    ;; Load breakpoints on startup
    (after-init . dape-breakpoint-load)

    :custom
    ;; Turn on global bindings for setting breakpoints with mouse
    (dape-breakpoint-global-mode +1)

    ;; Info buffers to the right
    (dape-buffer-window-arrangement 'right)
    ;; Info buffers like gud (gdb-mi)
    ;; (dape-buffer-window-arrangement 'gud)
    (dape-info-hide-mode-line nil)

    ;; Projectile users
    ;; (dape-cwd-function #'projectile-project-root)

    :config
    ;; Pulse source line (performance hit)
    ;; (add-hook 'dape-display-source-hook #'pulse-momentary-highlight-one-line)

    ;; Save buffers on startup, useful for interpreted languages
    ;; (add-hook 'dape-start-hook (lambda () (save-some-buffers t t)))

    ;; Kill compile buffer on build success
    (add-hook 'dape-compile-hook #'kill-buffer))

  ;; Left and right side windows occupy full frame height
  (use-package emacs
    :custom
    (window-sides-vertical t))
#+end_src

**** TypeScript

This is a basic configuration for the TypeScript language so that =.ts= files activate =typescript-mode= when opened.  We're also adding a hook to =typescript-ts-mode-hook= to call =eglot-ensure= so that we activate =eglot= to get LSP features every time we edit TypeScript code.

#+begin_src emacs-lisp
  (use-package typescript-mode
    :mode "\\.ts\\'"
    :hook (typescript-ts-mode . eglot-ensure)
    :config
    (setq typescript-indent-level 2))
#+end_src

*Important note!*  For =eglot= to work with TypeScript (and JavaScript) you will need to install a language server on your machine.  If you have Node.js installed, the easiest way to do that is by running the following command:

#+begin_src shell :tangle no
  npm install -g typescript-language-server typescript
#+end_src

This will install the [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]] and the TypeScript compiler package.

**** Python

Make sure you have the =pyls= language server installed before trying =eglot=!

#+begin_src sh :tangle no
  pip install --user "python-language-server[all]"
#+end_src

There are a number of other language servers for Python if you find that =pyls= doesn't work for you.

#+begin_src emacs-lisp
  (use-package python-mode
    :mode "\\.py\\'"
    :hook (python-ts-mode . eglot-ensure))
#+end_src

You can use the pyvenv package to use =virtualenv= environments in Emacs.

#+begin_src emacs-lisp
  (use-package pyvenv
    :after python-mode
    :config
    (pyvenv-mode 1))
#+end_src

**** C/C++

Sets the default behavior for C and C++ mode styles. Clangd is used as the lsp for C and C++. Make sure it is installed on your host!!

#+begin_src emacs-lisp
  (use-package cc-mode
    :bind (:map c-mode-base-map
  	      ("<RET>" . c-context-line-break))
    :custom
    (c-default-style
     ((awk-mode . "awk")
      (java-mode . "java")
      (other . "linux")))
    (c-basic-offset 4)
    (c-cleanup-list
     '(brace-else-brace
       brace-elseif-brace
       brace-catch-brace
       defun-close-semi
       list-close-comma
       scope-operator
       compact-empty-funcall
       comment-close-slash))
    :config
    (c-toggle-syntactic-indentation 1)
    (c-toggle-hungry-state 1)
    (c-toggle-auto-newline 1)
    :hook
    ((c-mode . eglot-ensure)
     (c++-mode . eglot-ensure)
     (c-mode . electric-indent-local-mode)))
#+end_src

**** Go

Go is a simple language made by Google to be an alternative to C/C++

#+begin_src emacs-lisp
  (add-hook 'go-ts-mode-hook #'eglot-ensure)
#+end_src

**** Zig

[[https://github.com/ziglang/zig-mode][Zig-mode]] provides syntax highlighting and automatic indentation for Zig in Emacs. 

#+begin_src emacs-lisp
  (use-package zig-mode
    :mode "\\.zig\\'")
#+end_src

**** Racket

Racket is a general-purpose, multi-paradigm programming language in the Lisp family.

#+begin_src emacs-lisp
  (use-package racket-mode
    :demand)
#+end_src

**** Nix

[[https://nixos.org/][Nix]] is a declarative language used for project dependency reproduction, that can use [[https://search.nixos.org/packages][nixpkgs]] as its package manager. NixOS extends Nix to declare entire systems using the language and packages. Nix also enables use of flakes for generating lock-files to increase reproducibility and is the preferred way of writing nix.

***** nix-mode
[[https://github.com/NixOS/nix-mode][nix-mode]] is the major mode for the nix language. Also includes nix-unpack to unpack a source of a nix attribute with =M-x attribute= followed by your nix path and attribute path as well as nix-build to build nix derivations similar to =M-x compile=, building in the current directory if there is a default.nix present.nix.el also provides some basic functions for interfacing with Nix. Some variables are provided to point to the Nix binaries that can be used in Lisp code:

nix-executable
nix-build-executable
nix-instantiate-executable
nix-store-executable
nix-shell-executable

Other useful functions for Lisp scripts are provided:
nix-system - Get the current system, detected by Nix

nix-flake.el provides support for flake commands. These commands are experimental as of Nix 2.4. It uses transient.el to provide a magit-like interface. To run a command on the current flake, type:
M-x nix-flake

You can also initialize a flake from a template:
M-x nix-flake-init

nix-repl.el has two purposes.
First, it provides an interface for completion, used by nix-company.el.
Second, it provides an interactive function to open a repl. You can open this with:
M-x nix-repl

nix-store provides a command M-x nix-store-show-path. The command displays an overview of a store path. The information it shows is the realization status, the hash and the size of the store path. Also it shows lists of derivers, references, referrers and requisites of the respective path.
You can change the order in which that information is shown. See the documentation of the function nix-store-show-path for more information.
When viewing a store buffer, the command M-x nix-store-show-log opens a local log file associated with a derivation.
When nix-prettify-mode is enabled, hash-parts of the Nix store file names are prettified, i.e. displayed as nix-prettify-char character (… by default.).

#+begin_src emacs-lisp
  (use-package nix-mode
    :after eglot
    :hook
    (nix-mode . eglot-ensure)
    :mode "\\.nix\\'")
#+end_src

***** nixfmt

[[https://github.com/purcell/emacs-nixfmt][nixfmt]] is the endorsed formatter for nix code using the nixfmt command. Requires the separate nixfmt package!!

#+begin_src emacs-lisp
  (use-package nixfmt
    :after nix-mode
    :bind ("C-c C-f" . nixfmt-buffer))

  (add-hook 'nix-mode-hook 'nixfmt-on-save-mode)  
#+end_src

**** Emacs Lisp

Emacs Lisp is the Lisp dialect used to provide the Emacs environment and is the main feature of Emacs, with only C being the other language used for Emacs. Built-in tooling exists for Emacs Lisp, along with other Lisp dialects.

#+begin_src emacs-lisp
  (keymap-set lisp-mode-shared-map "C-c C-p" #'check-parens)
  (keymap-set emacs-lisp-mode-map "C-c d" #'edebug-mode)
#+end_src

***** SLIME

[[https://github.com/slime/slime][SLIME]] is The Superior Lisp Interaction Mode for Emacs, a replacement for the built-in inferior list interaction mode and features support for many CLisp variations.

#+begin_src emacs-lisp
  (use-package slime
    :demand
    :custom
    (inferior-lisp-program "sbcl"))
#+end_src

**** Guile

GNU Guile is GNU's implementation of Scheme. Geiser is a collection of Emacs major and minor modes that conspire with one or more Scheme interpreters to keep the Lisp Machine Spirit alive. It draws inspiration (and a bit more) from environments such as Common Lisp’s Slime, Factor’s FUEL, Squeak or Emacs itself, and does its best to make Scheme hacking inside Emacs (even more) fun.

#+begin_src emacs-lisp
  (use-package geiser-guile
    :demand
    :custom
    (geiser-guile-binary "guile")
    (geiser-guile-load-path '(".")))
#+end_src
**** GLSL

GLSL is the shader language for OpenGL. [[https://github.com/jimhourihan/glsl-mode][GLSL mode]] is self explanatory.

#+begin_src emacs-lisp
  (use-package glsl-mode
    :demand)
#+end_src

**** Haskell

[[https://github.com/haskell/haskell-mode][Haskell mode]] is a major mode for editing, developing, and debugging Haskell programs.

#+begin_src emacs-lisp
  (use-package haskell-mode
    :demand)
#+end_src

**** KBD

[[https://github.com/chmouel/kanata-kbd-mode/][Kanata-KBD-Mode]] provides a major mdoe for syntax highlighting of .kbd files used in Kanata configuration files.

#+begin_src emacs-lisp
  (use-package kanata-kbd-mode
    :demand)
#+end_src

*** Version Control
**** Magit

[[https://magit.vc/][Magit]] is a git porcelain, displaying git in a tui state within an org-mode buffer.

#+begin_src emacs-lisp
  (use-package magit
    :after transient
    :commands magit-status
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  (use-package ghub
    :demand)

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge
    :after magit
    :custom
    (auth-sources '("~/.authinfo")))
#+end_src

**** Git Modes

[[https://github.com/magit/git-modes][Git modes]] contains, well... major modes for editing git configurations files!

#+begin_src emacs-lisp
  (use-package git-modes)
#+end_src

**** Consult-gh
[[https://github.com/armindarvish/consult-gh?tab=readme-ov-file][Consult-gh]] is an interface to GitHub using the GitHub CLI and Consult (and optionally embark and forge).

#+begin_src emacs-lisp
  (use-package consult-gh
    :after consult
    :custom
    (consult-gh-default-clone-directory "~/projects")
    (consult-gh-show-preview t)
    (consult-gh-preview-key "C-o")
    (consult-gh-repo-action #'consult-gh--repo-browse-files-action)
    (consult-gh-large-file-warning-threshold 2500000)
    (consult-gh-confirm-name-before-fork nil)
    (consult-gh-confirm-before-clone t)
    (consult-gh-notifications-show-unread-only nil)
    (consult-gh-default-interactive-command #'consult-gh-transient)
    (consult-gh-prioritize-local-folder nil)
    (consult-gh-group-dashboard-by :reason)
    ;;;; Optional
    (consult-gh-repo-preview-major-mode nil) ; show readmes in their original format
    (consult-gh-preview-major-mode 'org-mode) ; use 'org-mode for editing comments, commit messages, ...
    :config
    ;; Remember visited orgs and repos across sessions
    (add-to-list 'savehist-additional-variables 'consult-gh--known-orgs-list)
    (add-to-list 'savehist-additional-variables 'consult-gh--known-repos-list)
    ;; Enable default keybindings (e.g. for commenting on issues, prs, ...)
    (consult-gh-enable-default-keybindings))


  ;; Install `consult-gh-embark' for embark actions
  (use-package consult-gh-embark
    :config
    (consult-gh-embark-mode +1))


  ;; Install `consult-gh-forge' for forge actions
  (use-package consult-gh-forge
    :config
    (consult-gh-forge-mode +1)
    (setq consult-gh-forge-timeout-seconds 20))
#+end_src

**** Auto Commit Mode

[[https://github.com/ryuslash/git-auto-commit-mode][Auto commit mode]] allows for automatic commits upon file saving, where the saved file is the name of the commit relative to the root of the project. This is especially useful for projects that are more notes oriented, like an org roam zettelkasten. It can also automate pushes to remotes.

Simply create a dir-locals.el function in the desired directory with the code =((nil . ((eval git-auto-commit-mode 1))))=.

#+begin_src emacs-lisp
  ;; (use-package git-auto-commit-mode
  ;;   :demand
  ;;   :custom
  ;;   ((gac-automatically-push-p t)
  ;;    (gac-automatically-add-new-files-p t)))
#+end_src

**** Ediff
Ediff is a built-in package for checking the difference between two files. Works well with version controlled files for things like merge conflicts

#+begin_src emacs-lisp
  (use-package ediff
    :demand
    :custom
    (ediff-keep-variants nil)
    (ediff-window-setup-function 'ediff-setup-windows-plain)
    (ediff-split-window-function 'split-window-horizontally))
#+end_src

*** Environment

Emacs often will need the environment variables that are within the shell, but they are not always passed to it. [[https://github.com/purcell/exec-path-from-shell][exec-path-from-shell]] resolves this and is compatible with [bash, zsh, tcsh, fish, nu] shells. I personally run bash as my Emacs shell for portability when not using Eshell.

#+begin_src emacs-lisp
  (use-package exec-path-from-shell
    :demand
    :custom
    (exec-path-from-shell-variables '("PATH"
                                      "MANPATH"
                                      "SSH_AUTH_SOCK"
                                      "PYTHONPATH"
                                      "LANG"
                                      "LC_ALL"
                                      "SSH_AGENT_PID"
                                      "GPG_AGENT_INFO"
                                      "NIX_SSL_CERT_FILE"
                                      "NIX_PATH"))
    :config
    (exec-path-from-shell-initialize))
#+end_src

*** Envrc

[[https://github.com/purcell/envrc][Envrc]] is an external package that has an Emacs package as well to pass the current file's environment to Emacs, allowing programs started within Emacs, such as inferior shells or linters, to have the correct $PATH and environment variables. Ensure that the external Direnv package is installed!!

#+begin_src emacs-lisp
  (use-package envrc
    :demand
    :hook (after-init . envrc-global-mode))
#+end_src

*** SSH

SSH allows remote access to other computers and is critical in software like git when using GitHub. [[https://github.com/magit/ssh-agency][SSH Agency]] helps set ssh variables for Windows upon startup along with allowing Unix-like systems to delay having to enter the passphrase until the first push to remote.

#+begin_src emacs-lisp
  (use-package ssh-agency
    :demand)
#+end_src

** Misc
*** SICP

SICP, or the Structure and Interpretation of Computer Programs, is a legendary programming book written in MIT Scheme. Luckily, there is even a MELPA package for an TeXinfo file for native Emacs viewing and use in Info! Racket offers the SICP Collection, a Racket #lang that makes it fully compatible with SICP code. Requires external raco package!!

#+begin_src emacs-lisp
  (use-package sicp
    :after info)
#+end_src

*** Crux

[[https://github.com/bbatsov/crux][Crux]] contains a variety of useful commands.

#+begin_src emacs-lisp
  (use-package crux
    :demand
    :bind
    ("C-k"     . #'crux-smart-kill-line)
    ("C-c o"   . #'crux-smart-open-line-above)
    ("C-c F"   . #'crux-recentf-find-directory)
    ("s-4 t" . #'crux-transpose-windows)
    ("C-c d"   . #'crux-duplicate-current-line-or-region)
    ("C-c M-d" . #'crux-duplicate-and-comment-current-line-or-region)
    ("M-o"     . #'crux-other-window-or-switch-buffer))
#+end_src

*** Emacs

Here is a general configuration for built-in Emacs settings and modes not in a package.

#+begin_src emacs-lisp
  (use-package emacs
    :demand
    :bind
    ("C-z" . repeat)
    :custom
    (bidi-inhibit-bpa t)
    (redisplay-skip-fontification-on-input t)
    (save-interprogram-paste-before-kill t)
    (kill-do-not-save-duplicates t)
    (reb-re-syntax 'string)
    (ffap-machine-p-known 'reject)
    (window-combination-resize t)
    (set-mark-command-repeat-pop t)
    (help-window-select t)
    (epg-pinentry-mode 'loopback)
    :config
    (setq-default bidi-display-reordering t
    		bidi-paragraph-direction 'left-to-right)
    (keymap-set key-translation-map "s-<f1>" '"<f1>") ;; Ensure F1 works on dual function key keyboards (e.g. laptops)
    (global-subword-mode 1)
    (repeat-mode 1)
    (save-place-mode 1)
    (global-auto-revert-mode 1)
    (winner-mode 1)
    (add-hook 'after-save-hook
              #'executable-make-buffer-file-executable-if-script-p)
    (advice-add 'save-place-find-file-hook :after
                (lambda (&rest _)
  		(when buffer-file-name (ignore-errors (recenter))))))

  (defun toggle-delete-other-windows ()
    "Delete other windows in frame if any, or restore previous window config."
    (interactive)
    (if (and winner-mode
             (equal (selected-window) (next-window)))
        (winner-undo)
      (delete-other-windows)))

  (keymap-global-set "s-1" #'toggle-delete-other-windows)
#+end_src

* Minimal Configuration
:PROPERTIES:
:header-args:emacs-lisp: :tangle ./minimal-init.el
:END:

For the cases where I am unable to run Emacs on my Guix systems, I am providing a minimal configuration that will focus on portability above else. It will be able to work in both the terminal and as a GUI if available, although it will not feature GUI reliance.

#+begin_src emacs-lisp

#+end_src

* End Initialization
:PROPERTIES:
:header-args:emacs-lisp: :tangle ./init.el
:END:

Properly resetting the GC.

#+begin_src emacs-lisp
  (setq gc-cons-threshold (* 800 1000)) ; 800KB default
#+end_src

