#+TITLE: Emacs Configuration File
#+PROPERTY: header-args:emacs-lisp :tangle "~/.config/emacs/init.el"

This org document serves as the configuration of emacs, tangling babel code into init.el with =C-c C-v t= (Tangle) and =C-c r i= (Reload init.el).

* Startup Performance

#+begin_src emacs-lisp

  ;; The default is 800 kilobytes.  Measured in bytes.
  (setq gc-cons-threshold (* 50 1000 1000))

  (defun display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                       (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'display-startup-time)

#+end_src

* Package System Setup
Emacs has a built in package manager but it doesn't make it easy to automatically install packages on a new system the first time you pull down your configuration.  [[https://github.com/jwiegley/use-package][use-package]] is a really helpful package used in this configuration to make it a lot easier to automate the installation and configuration of everything else we use. [[https://github.com/radian-software/straight.el][Straight.el]] is a purely functional package manager that can be used alongside use-package for things like github packages. Straight.el can also be used for creating 'distros' of Emacs like with nix, but with greater flexibility.

#+begin_src emacs-lisp
  (defvar bootstrap-version)
  (let ((bootstrap-file
         (expand-file-name
          "straight/repos/straight.el/bootstrap.el"
          (or (bound-and-true-p straight-base-dir)
              user-emacs-directory)))
        (bootstrap-version 7))
    (unless (file-exists-p bootstrap-file)
      (with-current-buffer
          (url-retrieve-synchronously
           "https://raw.githubusercontent.com/radian-software/straight.el/develop/install.el"
           'silent 'inhibit-cookies)
        (goto-char (point-max))
        (eval-print-last-sexp)))
    (load bootstrap-file nil 'nomessage))

  (straight-use-package 'use-package)
  (setq straight-use-package-by-default t)
#+end_src
* Keep Folders Clean
We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean!  It knows about a wide variety of variables for built in Emacs features as well as those from community packages so it can be much easier than finding and setting these variables yourself.

#+begin_src emacs-lisp

  ;; NOTE: If you want to move everything out of the ~/.emacs.d folder
  ;; reliably, set `user-emacs-directory` before loading no-littering!
  (setq user-emacs-directory "~/.cache/emacs")

  (use-package no-littering
    
    :config
    ;; Backup files
    (setq backup-directory-alist
  	`((".*" . ,(no-littering-expand-var-file-name "backup/"))))
    ;; Autosave files
    (setq auto-save-file-name-transforms
  	`((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))
    ;; Lock files
    (setq lock-file-name-transforms
  	`((".*" ,(no-littering-expand-var-file-name "lock-files/") t))))


  ;; excluding no-littering directories from recentf
  (require 'recentf)
  (add-to-list 'recentf-exclude
               (recentf-expand-file-name no-littering-var-directory))
  (add-to-list 'recentf-exclude
               (recentf-expand-file-name no-littering-etc-directory))

#+end_src
* Keybinding
** Custom Binds
A set of bindings not set for packages.

#+begin_src emacs-lisp

  ;; Make ESC quit prompts
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

  ;; Opens this config file
  (global-set-key (kbd "C-c f d e") '(lambda () "Opens org-literate init.el file." (interactive) (find-file (expand-file-name "Emacs.org" (file-name-directory user-init-file)))))

  ;; Shortcut to reload init.el
  (defun reload-init-el ()
    "Loads init.el the same as M-x load-file, reloading Emacs' configuration. Note that not all changes may occur immediately and may require Emacs to be restarted."
    (interactive)
    (load-file user-init-file)
    (message "Init file reloaded"))
  (global-set-key (kbd "C-c r i") 'reload-init-el)

#+end_src
** Misc Modes

#+begin_src emacs-lisp
  (setq sub-word-mode t)
  (setq repeat-mode t)
#+end_src

* UI Configuration
** Basic UI
Defaults for GNU Emacs ui, excluding external packages.

#+begin_src emacs-lisp

  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room
  (menu-bar-mode -1)          ; Disable the menu bar
  (setq visible-bell t)       ; Set up the visible bell

  (column-number-mode)
  (setq display-line-numbers t)
  (setq display-line-numbers-width-start t)

  ;; Set frame transparency
  ;; (set-frame-parameter (selected-frame) 'alpha frame-transparency)
  ;; (add-to-list 'default-frame-alist `(alpha . ,frame-transparency))
  ;; (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  ;; (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
  		term-mode-hook
  		shell-mode-hook
  		treemacs-mode-hook
  		eshell-mode-hook))
    (add-hook mode (lambda () (setq display-line-numbers nil))))

#+end_src
** Theme
[[https://github.com/catppuccin/emacs][catppuchin]] is the chosen theme of Emacs. Options for flavor are: 'latte (light), 'frappe, 'macchiato, 'mocha (darkest)

#+begin_src emacs-lisp

  (straight-use-package 'catppuccin-theme)
  (load-theme 'catppuccin :no-confirm)
  (setq catppuccin-flavor 'mocha)
  (catppuccin-reload)

#+end_src
** Better Modeline
[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a very attractive and rich (yet still minimal) mode line configuration for Emacs.  The default configuration is quite good but you can check out the [[https://github.com/seagle0128/doom-modeline#customize][configuration options]] for more things you can enable or disable.

*NOTE:* The first time you load your configuration on a new machine, you'll need to run =M-x all-the-icons-install-fonts= so that mode line icons display correctly.

#+begin_src emacs-lisp

  (use-package all-the-icons)

  (use-package doom-modeline
    :init (doom-modeline-mode t)
    :config
    (setq doom-modeline-height 15)
    (setq doom-modeline-window-width-limit fill-column)
    (setq doom-modeline-project-detection 'auto)
    (setq doom-modeline-buffer-file-name-style 'auto)
    (setq doom-modeline-icon t)
    (setq doom-modeline-major-mode-icon t)
    (setq doom-modeline-major-mode-color-icon t)
    (setq doom-modeline-buffer-state-icon t )
    (setq doom-modeline-buffer-modification-icon t )
    (setq doom-modeline-lsp-icon t)
    (setq doom-modeline-time-icon t)
    (setq doom-modeline-time-live-icon t)
    (setq doom-modeline-unicode-number t)
    (setq doom-modeline-unicode-fallback nil)
    (setq doom-modeline-buffer-name t)
    (setq doom-modeline-highlight-modified-buffer-name nil)
    (setq doom-modeline-column-zero-based nil)
    (setq doom-modeline-minor-modes nil)
    (setq doom-modeline-selection-info t)
    (setq doom-modeline-enable-word-count nil)
    (setq doom-modeline-enable-buffer-position t)
    (setq doom-modeline-buffer-encoding t)
    (setq doom-modeline-indent-info t)
    (setq doom-modeline-total-line-number nil)

    ;; VCS Display
    (setq doom-modeline-vcs-icon t)
    (setq doom-modeline-vcs-max-length 15)
    (setq doom-modeline-vcs-display-function #'doom-modeline-vcs-name)
    (setq doom-modeline-vcs-state-faces-alist
      '((needs-update . (doom-modeline-warning bold))
        (removed . (doom-modeline-urgent bold))
        (conflict . (doom-modeline-urgent bold))
        (unregistered . (doom-modeline-urgent bold))))
    (with-eval-after-load 'ghub
      (setq doom-modeline-github t) ;; Requires `ghub' package
      (setq doom-modeline-github-interval(* 30 60))) ;; minutes * seconds/minute (Only alter highest unit of time. No 30 second minutes!)

    (setq doom-modeline-check-icon t)
    (setq doom-modeline-check 'auto)
    (setq doom-modeline-number-limit 99)
    (setq doom-modeline-project-name t)
    (setq doom-modeline-workspace-name t)
    (setq doom-modeline-persp-name t)
    (setq doom-modeline-display-default-persp-name nil)
    (setq doom-modeline-persp-icon t)
    (setq doom-modeline-lsp t)

    ;; Modal states (i.e. evil, god, overwrite, etc.)
    (setq doom-modeline-modal t)
    (setq doom-modeline-modal-icon t)
    (setq doom-modeline-modal-mordern-icon t)
    
    (setq doom-modeline-always-show-macros-register t)

    ;; GNUs
    (setq doom-modeline-gnus t)
    (setq doom-modeline-gnus-timer 2)
    (setq doom-modeline-gnus-excluded-groups '("dummy.group"))

    ;;IRC
    (setq doom-modeline-irc t)
    (setq doom-modeline-irc-stylize 'identity)

    (setq doom-modeline-battery nil)
    (setq doom-modeline-time nil)
    (setq doom-modeline-display-misc-in-all-mode-lines t)
    (setq doom-modeline-remote-host t)
    (setq doom-modeline-buffer-file-name-function #'identity)
    (setq doom-modeline-buffer-file-truename-function #'identity)
    (setq doom-modeline-env-version t)
    

#+end_src

** Which Key
[[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))

#+end_src
** Vertico
[[https://github.com/minad/vertico][Vertico]] is a minimal completion UI that uses built-in Emacs completion, performing similarly to Ivy and Helm, but with normal Emacs configuration and lower overhead.

#+begin_src emacs-lisp

  (use-package vertico
    
    :init
    (vertico-mode))

  ;; Persistant history over different Emacs sessions
  (use-package savehist
    
    :init
    (savehist-mode))

  ;; Enables context menu. `vertico-multiform-mode' adds a menu in the minibuffer to switch display modes
  (setq context-menu-mode t)
  ;; Support opening new minibuffers from inside existing minibuffers
  (setq enable-recursive-minibuffers t)
  ;; Hide commands in M-x which do not work in the current mode.  Vertico
  ;; commands are hidden in normal buffers. This setting is useful beyond
  ;; Vertico.
  (setq read-extended-command-predicate #'command-completion-default-include-p)
  ;; Do not allow the cursor in the minibuffer prompt
  (setq minibuffer-prompt-properties
   '(read-only t cursor-intangible t face minibuffer-prompt)))

#+end_src

** Marginalia
[[https://github.com/minad/marginalia][Marginalia]] adds to minibuffer completions in annotations, providing additional context.

#+begin_src emacs-lisp

  (use-package marginalia
    
    :bind (:map minibuffer-local-map
  	      ("M-A" . marginalia-cycle))
    :init
    (marginalia-mode)) ;; Must be activated in :init

#+end_src

** Consult
[[https://github.com/minad/consult][Consult]] provides search and navigation commands like Counsel does with Ivy, but using the Emacs built in completion system like Vertico does.

#+begin_src emacs-lisp

  (use-package consult
    
    :bind (;; C-c bindings in `mode-specific-map'
           ("C-c M-x" . consult-mode-command)
           ("C-c h" . consult-history)
           ("C-c k" . consult-kmacro)
           ("C-c m" . consult-man)
           ("C-c i" . consult-info)
           ([remap Info-search] . consult-info)
           ;; C-x bindings in `ctl-x-map'
           ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
           ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
           ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
           ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
           ("C-x t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
           ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
           ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
           ;; Custom M-# bindings for fast register access
           ("M-#" . consult-register-load)
           ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
           ("C-M-#" . consult-register)
           ;; Other custom bindings
           ("M-y" . consult-yank-pop)                ;; orig. yank-pop
           ;; M-g bindings in `goto-map'
           ("M-g e" . consult-compile-error)
           ("M-g r" . consult-grep-match)
           ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
           ("M-g g" . consult-goto-line)             ;; orig. goto-line
           ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
           ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
           ("M-g m" . consult-mark)
           ("M-g k" . consult-global-mark)
           ("M-g i" . consult-imenu)
           ("M-g I" . consult-imenu-multi)
           ;; M-s bindings in `search-map'
           ("M-s d" . consult-find)                  ;; Alternative: consult-fd
           ("M-s c" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . consult-ripgrep)
           ("M-s l" . consult-line)
           ("M-s L" . consult-line-multi)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)
           ;; Isearch integration
           ("M-s e" . consult-isearch-history)
           :map isearch-mode-map
           ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
           ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
           ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
           ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
           ;; Minibuffer history
           :map minibuffer-local-map
           ("M-s" . consult-history)                 ;; orig. next-matching-history-element
           ("M-r" . consult-history))                ;; orig. previous-matching-history-element

    ;; The :init configuration is always executed (Not lazy)
    :init

    ;; Tweak the register preview for `consult-register-load',
    ;; `consult-register-store' and the built-in commands.  This improves the
    ;; register formatting, adds thin separator lines, register sorting and hides
    ;; the window mode line.
    (advice-add #'register-preview :override #'consult-register-window)
    (setq register-preview-delay 0.5)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)

    ;; Configure other variables and modes in the :config section,
    ;; after lazily loading the package.
    :config

    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    ;; (setq consult-preview-key 'any)
    ;; (setq consult-preview-key "M-.")
    ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    (consult-customize
     consult-theme :preview-key '(:debounce 0.2 any)
     consult-ripgrep consult-git-grep consult-grep consult-man
     consult-bookmark consult-recent-file consult-xref
     consult-source-bookmark consult-source-file-register
     consult-source-recent-file consult-source-project-recent-file
     ;; :preview-key "M-."
     :preview-key '(:debounce 0.4 any))

    ;; Optionally configure the narrowing key.
    ;; Both < and C-+ work reasonably well.
    (setq consult-narrow-key "<")) ;; "C-+"

    ;; Optionally make narrowing help available in the minibuffer.
    ;; You may want to use `embark-prefix-help-command' or which-key instead.
    ;; (keymap-set consult-narrow-map (concat consult-narrow-key " ?") #'consult-narrow-help)
    

#+end_src

** Embark
- [[https://github.com/oantolin/embark][Embark]] provides minibuffer actions and a context menu, making it easy to choose a command based on what is near the point with  =embark-act= with =C-.=, like a right-click context menu. Running =embark-dwim= with =C-;= runs the default action instead.

  #+begin_src emacs-lisp

    (use-package embark
      
      :bind
      (("C-."   . embark-act)
       ("C-;"   . embark-dwim)
       ("C-h B" . embark-bindings))
      :init
      (setq prefix-help-command #'embark-prefix-help-command)
      (add-hook 'context-menu-functions #'embark-context-menu 100)
      (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
      (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)
      :config
      ;; Hide the mode line of the Embark live/completions buffers
      (add-to-list 'display-buffer-alist
    	       '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
    		 nil
    		 (window-parameters (mode-line-format . none)))))

    (use-package embark-consult
      :after
      consult
      embark
      )
      

  #+end_src

** Orderless
[[https://github.com/oantolin/orderless][Orderless]] provides an orderless completion style. Used with Vertico.

#+begin_src emacs-lisp

  (use-package orderless
  
  :custom
  ;; Configure a custom style dispatcher (see the Consult wiki)
  ;; (orderless-style-dispatchers '(+orderless-consult-dispatch orderless-affix-dispatch))
  ;; (orderless-component-separator #'orderless-escapable-split-on-space)
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles partial-completion))))
  (completion-category-defaults nil) ;; Disable defaults, use our settings
  (completion-pcm-leading-wildcard t)) ;; Emacs 31: partial-completion behaves like substring

#+end_src

** Helpful Help Commands
[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of very helpful (get it?) information to Emacs' =describe-= command buffers.  For example, if you use =describe-function=, you will not only get the documentation about the function, you will also see the source code of the function and where it gets used in other places in the Emacs configuration.  It is very useful for figuring out how things work in Emacs.

#+begin_src emacs-lisp

  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src

** Text Scaling
This is an example of using [[https://github.com/abo-abo/hydra][Hydra]] to design a transient key binding for quickly adjusting the scale of the text on screen.  We define a hydra that is bound to =C-s t s= and, once activated, =j= and =k= increase and decrease the text scale.  You can press any other key (or =f= specifically) to exit the transient key map.

#+begin_src emacs-lisp

  (use-package hydra
    :defer t)

  (defhydra hydra-text-scale (:timeout 4)
    "scale text"
    ("j" text-scale-increase "in")
    ("k" text-scale-decrease "out")
    ("f" nil "finished" :exit t))

  (global-set-key (kbd "C-c t s") '(hydra-text-scale/body :which-key "scale text"))

#+end_src

** Windowing
Emac's default window selection can be tough to intuit at times. Using windmove, keybindings for using =M-<direction>= allows focus to shift to the frame in =<direction>=.

#+begin_src emacs-lisp

  (global-set-key (kbd "M-s <left>")  'windmove-left)
  (global-set-key (kbd "M-s <right>") 'windmove-right)
  (global-set-key (kbd "M-s <up>")    'windmove-up)
  (global-set-key (kbd "M-s <down>")  'windmove-down)

#+end_src
* Org Mode
[[https://orgmode.org/][Org Mode]] is one of the hallmark features of Emacs.  It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.
** Better Font Faces
The =org-font-setup= function configures various text faces to tweak the sizes of headings and use variable width fonts in most cases so that it looks more like we're editing a document in =org-mode=.  We switch back to fixed width (monospace) fonts for code blocks and tables so that they display correctly. Cantarell is the used font, so ensure it is installed on the system.

#+begin_src emacs-lisp

  (defun org-font-setup ()
    ;; Set faces for heading levels
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil    :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-table nil    :inherit 'fixed-pitch)
    (set-face-attribute 'org-formula nil  :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil     :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil    :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil  :inherit 'fixed-pitch)
    (set-face-attribute 'line-number nil :inherit 'fixed-pitch)
    (set-face-attribute 'line-number-current-line nil :inherit 'fixed-pitch))

#+end_src
** Basic Config
This section contains the basic configuration for =org-mode=, setting up proper modes and formatting.

#+begin_src emacs-lisp

  (use-package org
    :straight nil
    :commands (org-capture org-agenda)
    :hook (org-mode . org-indent-mode)
          (org-mode . variable-pitch-mode)
  	(org-mode . visual-line-mode)
    :init
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
  			    '(("^ *\\([-]\\) "
  			       (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

    :config
    (setq org-ellipsis " ▾"))

#+end_src

*** Nicer Heading Bullets
[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading stars in =org-mode= buffers with nicer looking characters that you can control.

#+begin_src emacs-lisp

  (use-package org-bullets
    :after org
    
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))

#+end_src

** Configure Babel Languages
To execute or export code in =org-mode= code blocks, you'll need to set up =org-babel-load-languages= for each language you'd like to use.  [[https://orgmode.org/worg/org-contrib/babel/languages.html][This page]] documents all of the languages that you can use with =org-babel=.

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    (org-babel-do-load-languages
     'org-babel-load-languages
     '((emacs-lisp . t)
       (lisp . t)
       (C . t)
       (css . t)
       (shell . t)
       (eshell . t)
       (gnuplot . t)
       (python . t)))

    (push '("conf-unix" . conf-unix) org-src-lang-modes))

#+end_src

** Structure Templates
Org Mode's [[https://orgmode.org/manual/Structure-Templates.html][structure templates]] feature enables you to quickly insert code blocks into your Org files in combination with =org-tempo= by typing =<= followed by the template name like =el= or =py= and then press =TAB=.  For example, to insert an empty =emacs-lisp= block below, you can type =<el= and press =TAB= to expand into such a block.

You can add more =src= block templates below by copying one of the lines and changing the two strings at the end, the first to be the template name and the second to contain the name of the language [[https://orgmode.org/worg/org-contrib/babel/languages.html][as it is known by Org Babel]].

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    ;; This is needed as of Org 9.2
    (require 'org-tempo)

    (add-to-list 'org-structure-template-alist '("sh" . "src shell"))
    (add-to-list 'org-structure-template-alist '("lisp" . "src lisp"))
    (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
    (add-to-list 'org-structure-template-alist '("esh" . "src eshell"))
    (add-to-list 'org-structure-template-alist '("c" . "src C"))
    (add-to-list 'org-structure-template-alist '("cp" . "src C++"))
    (add-to-list 'org-structure-template-alist '("cs" . "src css"))
    (add-to-list 'org-structure-template-alist '("py" . "src python"))
    (add-to-list 'org-structure-template-alist '("gp" . "src gnuplot")))

#+end_src

** Auto-tangle Configuration Files
This snippet adds a hook to =org-mode= buffers so that =org-babel-tangle-config= gets executed each time such a buffer gets saved.  This function checks to see if the file being saved is the Emacs.org file you're looking at right now, and if so, automatically exports the configuration here to the associated output files. Make sure to git commit to snapshot versions!

#+begin_src emacs-lisp

  ;; Automatically tangle our Emacs.org config file when we save it
  (defun org-babel-tangle-config ()
    (when (and (string-equal (file-name-directory (buffer-file-name))
  			   (file-name-directory user-init-file))
  	     (string-equal "Emacs.org" (file-name-nondirectory buffer-file-name)))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'org-babel-tangle-config)))

#+end_src

** Org-Roam
[[https://www.orgroam.com/][Org-roam]] uses Org-mode with a SQLite to generate a node based note taking system, like Obsidian.md. [[https://www.youtube.com/watch?v=YxgA5z2R08I][This Video by System Crafters]] explains how to utilize Org-roam.

#+begin_src emacs-lisp

  (use-package org-roam
    :after org
    
    :init
    (setq org-roam-v2-ack t)
    :custom
    (org-roam-directory "~/Documents/zettelkasten")
    (org-roam-completion-everywhere t)
    (org-roam-capture-templates
     '(("d" "default" plain
        "%?"
        :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
        :unnarrowed t)
  	 ("n" "note" plain
  	  (file "~/roam/templates/note.org")
        :target (file+head "%<%Y%m%d%H%M%S>-${slug}.org" "#+title: ${title}\n")
  	  :unnarrowed t)))
    :bind (("C-c n l" . org-roam-buffer-toggle)
           ("C-c n f" . org-roam-node-find)
           ("C-c n i" . org-roam-node-insert)
           :map org-mode-map
           ("C-M-i" . completion-at-point))
    :config
    (org-roam-setup))

#+end_src

** Org-Roam-UI
[[https://github.com/org-roam/org-roam-ui][Org-Roam-UI]] Zettelkasten for Org-Roam, creating a graph like Obsidian.md for Roam nodes. =M-x org-roam-ui-mode RET= enables global mode and starts a web server. URL for web server is [[http://127.0.0.1:35901/]] 

#+begin_src emacs-lisp

  ;; Dependencies for Roam UI are websocket and simple-httpd
  (use-package simple-httpd)
  (use-package websocket)
  (use-package org-roam-ui
    :after
    (Org-Roam))

#+end_src

* Development
** Languages
*** LSP with Eglot
[[https://github.com/joaotavora/eglot][Eglot]] is the native Emac's lsp client. It can be run with [[https://github.com/blahgeek/emacs-lsp-booster][lsp-booster]] to convert JSON data into bytecode, massively speeding up Emac's interpreter and removing many stutters due to its single-threaded nature. Note that Emacs v30 introduced a JSON parser that decodes faster than bytecode, but has slower I/O. emacs-lsp-booster offers the option =--disable-bytecode=, which with setting =eglot-booster-io-only=t= will use to get the benefit of I/O buffering with the native JSON parser.

#+begin_src emacs-lisp

  (use-package eglot
    )

  ;; (use-package eglot-booster
  ;;   :after eglot
    
  ;;   :config (eglot-booster-mode))

#+end_src
*** Debugging with dape
[[https://github.com/svaante/dape][dape]] is the Debug Adapter Protocol for Emacs, functioning like dap-mode does. Invoking the =M-x dape= command begins a debugging session. Enabling repeat-mode and eldoc-mode is highly recommended.

#+begin_src emacs-lisp

  (use-package dape
    
    :preface
    ;; By default dape shares the same keybinding prefix as `gud'
    ;; If you do not want to use any prefix, set it to nil.
    (setq dape-key-prefix "\C-x\C-a")

    :hook
    ;; Save breakpoints on quit
    (kill-emacs . dape-breakpoint-save)
    ;; Load breakpoints on startup
    (after-init . dape-breakpoint-load)

    :custom
    ;; Turn on global bindings for setting breakpoints with mouse
    (dape-breakpoint-global-mode +1)

    ;; Info buffers to the right
    (dape-buffer-window-arrangement 'right)
    ;; Info buffers like gud (gdb-mi)
    ;; (dape-buffer-window-arrangement 'gud)
    (dape-info-hide-mode-line nil)

    ;; Projectile users
    ;; (dape-cwd-function #'projectile-project-root)

    :config
    ;; Pulse source line (performance hit)
    ;; (add-hook 'dape-display-source-hook #'pulse-momentary-highlight-one-line)

    ;; Save buffers on startup, useful for interpreted languages
    ;; (add-hook 'dape-start-hook (lambda () (save-some-buffers t t)))

    ;; Kill compile buffer on build success
    (add-hook 'dape-compile-hook #'kill-buffer))

  ;; For a more ergonomic Emacs and `dape' experience
  (use-package repeat
    :custom
    (repeat-mode +1))

  ;; Left and right side windows occupy full frame height
  (use-package emacs
    :custom
    (window-sides-vertical t))

#+end_src

*** TypeScript
This is a basic configuration for the TypeScript language so that =.ts= files activate =typescript-mode= when opened.  We're also adding a hook to =typescript-mode-hook= to call =eglot-ensure= so that we activate =eglot= to get LSP features every time we edit TypeScript code.

#+begin_src emacs-lisp

  (use-package typescript-mode
    :mode "\\.ts\\'"
    :hook (typescript-mode . eglot-ensure)
    :config
    (setq typescript-indent-level 2))

#+end_src

*Important note!*  For =eglot= to work with TypeScript (and JavaScript) you will need to install a language server on your machine.  If you have Node.js installed, the easiest way to do that is by running the following command:

#+begin_src shell :tangle no

npm install -g typescript-language-server typescript

#+end_src

This will install the [[https://github.com/theia-ide/typescript-language-server][typescript-language-server]] and the TypeScript compiler package.

*** Python
Make sure you have the =pyls= language server installed before trying =eglot=!

#+begin_src sh :tangle no

pip install --user "python-language-server[all]"

#+end_src

There are a number of other language servers for Python if you find that =pyls= doesn't work for you.

#+begin_src emacs-lisp

  (use-package python-mode
    
    :hook (python-mode . eglot-ensure))

#+end_src

You can use the pyvenv package to use =virtualenv= environments in Emacs.

#+begin_src emacs-lisp

  (use-package pyvenv
    :after python-mode
    :config
    (pyvenv-mode 1))

#+end_src

*** C/C++
Sets the default behaviour for C and C++ mode styles. Clangd is used as the lsp for C and C++. Make sure it is installed on your host!!

#+begin_src emacs-lisp

  (setq c-toggle-electric-state 1)
  (setq c-toggle-auto-hungry-state 1)
  (add-hook 'c-mode-hook 'eglot-ensure)
  (add-hook 'c++-mode-hook 'eglot-ensure)

#+end_src

*** Zig
[[https://github.com/ziglang/zig-mode][Zig-mode]] provdes syntax highlighting and automatic indentation for Zig in Emacs. 

#+begin_src emacs-lisp

  (use-package zig-mode
    
    :hook (zig-mode . eglot-ensure))

#+end_src

*** Racket
Racket is a general-purpose, multi-paradigm programming language in the Lisp family.

#+begin_src emacs-lisp

  (use-package racket-mode)

#+end_src

*** Gnuplot
[[http://www.gnuplot.info/][Gnuplot]] is a command-line and GUI program that can generate two- and three-dimensional plots of functions, data, and data fits. 

#+begin_src emacs-lisp
  (use-package gnuplot
    
    :config
    (setq read-extended-command-predicate #'command-completion-default-include-p))
#+end_src

*** Nix
[[https://nixos.org/][Nix]] is a declaritive language used for project dependency reproduction, that can use [[https://search.nixos.org/packages][nixpkgs]] as its package manager. NixOS extends Nix to declare entire systems using the language and packages. Nix also enables use of flakes for generating lockfiles to maximize reproducibility and is the preferred way of writing nix.
**** nix-mode
[[https://github.com/NixOS/nix-mode][nix-mode]] is the major mode for the nix language. Also includes nix-unpack to unpackack a source of a nix attribute with =M-x attribute= followed by your nix path and attribute path aswell as nix-build to build nix derivations similar to =M-x compile=, building in the current directory if there is a default.nix present.nix.el also provides some basic functions for interfacing with Nix. Some variables are provided to point to the Nix binaries that can be used in Lisp code:

    nix-executable
    nix-build-executable
    nix-instantiate-executable
    nix-store-executable
    nix-shell-executable

Other useful functions for Lisp scripts are provided:
    nix-system - Get the current system, detected by Nix

nix-flake.el provides support for flake commands. These commands are experimental as of Nix 2.4. It uses transient.el to provide a magit-like interface. To run a command on the current flake, type:
M-x nix-flake

You can also initialize a flake from a template:
M-x nix-flake-init

nix-repl.el has two purposes.
First, it provides an interface for completion, used by nix-company.el.
Second, it provides an interactive function to open a repl. You can open this with:
M-x nix-repl

nix-store provides a command M-x nix-store-show-path. The command displays an overview of a store path. The information it shows is the realisation status, the hash and the size of the store path. Also it shows lists of derivers, references, referrers and requisites of the respective path.
You can change the order in which that information is shown. See the documentation of the function nix-store-show-path for more information.
When viewing a store buffer, the command M-x nix-store-show-log opens a local log file associated with a derivation.
When nix-prettify-mode is enabled, hash-parts of the Nix store file names are prettified, i.e. displayed as nix-prettify-char character (… by default.).

#+begin_src emacs-lisp
  (use-package nix-mode
    
    :hook
    (nix-mode . eglot-ensure)
    :mode "\\.nix\\'")
#+end_src

**** nixfmt
[[https://github.com/purcell/emacs-nixfmt][nixfmt]] is the endorsed formatter for nix code using the nixfmt command. Requires the separate nixfmt package!!

#+begin_src emacs-lisp
  (use-package nixfmt
    :after nix-mode
    
    :bind ("C-c C-f" . nixfmt-buffer))

  (add-hook 'nix-mode-hook 'nixfmt-on-save-mode)  
#+end_src

**** nixd
[[https://github.com/nix-community/nixd][nixd]] is an lsp for nix using lsp-mode. Requires nixd package!!

#+begin_src emacs-lisp
  (add-to-list 'eglot-server-programs
  	     '(nix-mode . ("nixd")))
#+end_src

** LLM Integration
*** Ellama
[[https://github.com/s-kostyaev/ellama][Ellama]] allows integration between Emacs and [[https://ollama.com/][Ollama]]. The desired ollama model is pulled with the terminal command =ollama pull MODEL=.

#+begin_src emacs-lisp

  (use-package ellama
  
  :bind ("C-c e" . ellama)
  ;; send last message in chat buffer with C-c C-c
  :hook (org-ctrl-c-ctrl-c-final . ellama-chat-send-last-message)
  :init (setopt ellama-auto-scroll t)
  :config
  (setq ellama-provider
        (make-llm-ollama
         :host "https://localhost"
         :port 11434
         :chat-model "gpt-oss:20b"
         :embedding-model "gpt-oss:20b")))

#+end_src

** Corfu
[[https://github.com/minad/corfu][Corfu]] enhances in-buffer completion like Company mode does, instead using Emacs built-in completion like with Vertico.

#+begin_src emacs-lisp
  (use-package corfu
    
    ;; Optional customizations
    ;; :custom
    ;; (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match 'insert) ;; Configure handling of exact matches

    ;; Enable Corfu only for certain modes. See also `global-corfu-modes'.
    ;; :hook ((prog-mode . corfu-mode)
    ;;        (shell-mode . corfu-mode)
    ;;        (eshell-mode . corfu-mode))

    :init

    ;; Recommended: Enable Corfu globally.  Recommended since many modes provide
    ;; Capfs and Dabbrev can be used globally (M-/).  See also the customization
    ;; variable `global-corfu-modes' to exclude certain modes.
    (global-corfu-mode)

    ;; Enable optional extension modes:
    (corfu-history-mode)
    (corfu-popupinfo-mode))

  ;; A few more useful configurations...
  (use-package emacs
    :custom
    ;; TAB cycle if there are only few candidates
    ;; (completion-cycle-threshold 3)

    ;; Enable indentation+completion using the TAB key.
    ;; `completion-at-point' is often bound to M-TAB.
    (tab-always-indent 'complete)

    ;; Emacs 30 and newer: Disable Ispell completion function.
    ;; Try `cape-dict' as an alternative.
    (text-mode-ispell-word-completion nil)

    ;; Hide commands in M-x which do not apply to the current mode.  Corfu
    ;; commands are hidden, since they are not used via M-x. This setting is
    ;; useful beyond Corfu.
    (read-extended-command-predicate #'command-completion-default-include-p))
#+end_src

** Project.el
Project.el is the native project system for Emacs and is required for Eglot to function. Relies on vcs to determine projects.

** Magit

[[https://magit.vc/][Magit]] is a git porcelain, displaying git in a tui state within an org-mode buffer.

#+begin_src emacs-lisp

  (use-package magit
    :commands magit-status
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; NOTE: Make sure to configure a GitHub token before using this package!
  ;; - https://magit.vc/manual/forge/Token-Creation.html#Token-Creation
  ;; - https://magit.vc/manual/ghub/Getting-Started.html#Getting-Started
  (use-package forge
    :after magit)

#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is useful in programming modes because it colorizes nested parentheses and brackets according to their nesting depth.  This makes it a lot easier to visually match parentheses in Emacs Lisp code without having to count them yourself.

#+begin_src emacs-lisp

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode))

#+end_src
** Terminals
*** term-mode

=term-mode= is a built-in terminal emulator in Emacs.  Because it is written in Emacs Lisp, you can start using it immediately with very little configuration.  If you are on Linux or macOS, =term-mode= is a great choice to get started because it supports fairly complex terminal applications (=htop=, =vim=, etc) and works pretty reliably.  However, because it is written in Emacs Lisp, it can be slower than other options like =vterm=.  The speed will only be an issue if you regularly run console apps with a lot of output.

One important thing to understand is =line-mode= versus =char-mode=.  =line-mode= enables you to use normal Emacs keybindings while moving around in the terminal buffer while =char-mode= sends most of your keypresses to the underlying terminal.  While using =term-mode=, you will want to be in =char-mode= for any terminal applications that have their own keybindings.  If you're just in your usual shell, =line-mode= is sufficient and feels more integrated with Emacs.

With =evil-collection= installed, you will automatically switch to =char-mode= when you enter Evil's insert mode (press =i=).  You will automatically be switched back to =line-mode= when you enter Evil's normal mode (press =ESC=).

Run a terminal with =M-x term!=

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =C-c C-k= - Enter char-mode
- =C-c C-j= - Return to line-mode
- If you have =evil-collection= installed, =term-mode= will enter char mode when you use Evil's Insert mode

#+begin_src emacs-lisp

  (use-package term
    :commands term
    :config
    (setq explicit-shell-file-name "bash") ;; Change this to zsh, etc
    ;;(setq explicit-zsh-args '())         ;; Use 'explicit-<shell>-args for shell-specific args

    ;; Match the default Bash shell prompt.  Update this if you have a custom prompt
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *"))

#+end_src

**** Better term-mode colors

The =eterm-256color= package enhances the output of =term-mode= to enable handling of a wider range of color codes so that many popular terminal applications look as you would expect them to.  Keep in mind that this package requires =ncurses= to be installed on your machine so that it has access to the =tic= program.  Most Linux distributions come with this program installed already so you may not have to do anything extra to use it.

#+begin_src emacs-lisp

  (use-package eterm-256color
    :hook (term-mode . eterm-256color-mode))

#+end_src

*** vterm

[[https://github.com/akermu/emacs-libvterm/][vterm]] is an improved terminal emulator package which uses a compiled native module to interact with the underlying terminal applications.  This enables it to be much faster than =term-mode= and to also provide a more complete terminal emulation experience.

Make sure that you have the [[https://github.com/akermu/emacs-libvterm/#requirements][necessary dependencies]] installed before trying to use =vterm= because there is a module that will need to be compiled before you can use it successfully.

#+begin_src emacs-lisp

  (use-package vterm
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")  ;; Set this to match your custom shell prompt
    ;;(setq vterm-shell "zsh")                       ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000))

#+end_src

*** shell-mode

[[https://www.gnu.org/software/emacs/manual/html_node/emacs/Interactive-Shell.html#Interactive-Shell][shell-mode]] is a middle ground between =term-mode= and Eshell.  It is *not* a terminal emulator so more complex terminal programs will not run inside of it.  It does have much better integration with Emacs because all command input in this mode is handled by Emacs and then sent to the underlying shell once you press Enter.  This means that you can use =evil-mode='s editing motions on the command line, unlike in the terminal emulator modes above.

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =M-p= / =M-n= - go back and forward in the input history
- =C-c C-u= - delete the current input string backwards up to the cursor
- =counsel-shell-history= - A searchable history of commands typed into the shell

One advantage of =shell-mode= on Windows is that it's the only way to run =cmd.exe=, PowerShell, Git Bash, etc from within Emacs.  Here's an example of how you would set up =shell-mode= to run PowerShell on Windows:

#+begin_src emacs-lisp

  (when (eq system-type 'windows-nt)
    (setq explicit-shell-file-name "powershell.exe")
    (setq explicit-powershell.exe-args '()))

#+end_src

*** Eshell

[[https://www.gnu.org/software/emacs/manual/html_mono/eshell.html#Contributors-to-Eshell][Eshell]] is Emacs' own shell implementation written in Emacs Lisp.  It provides you with a cross-platform implementation (even on Windows!) of the common GNU utilities you would find on Linux and macOS (=ls=, =rm=, =mv=, =grep=, etc).  It also allows you to call Emacs Lisp functions directly from the shell and you can even set up aliases (like aliasing =vim= to =find-file=).  Eshell is also an Emacs Lisp REPL which allows you to evaluate full expressions at the shell.

The downsides to Eshell are that it can be harder to configure than other packages due to the particularity of where you need to set some options for them to go into effect, the lack of shell completions (by default) for some useful things like Git commands, and that REPL programs sometimes don't work as well.  However, many of these limitations can be dealt with by good configuration and installing external packages, so don't let that discourage you from trying it!

*Useful key bindings:*

- =C-c C-p= / =C-c C-n= - go back and forward in the buffer's prompts (also =[[= and =]]= with evil-mode)
- =M-p= / =M-n= - go back and forward in the input history
- =C-c C-u= - delete the current input string backwards up to the cursor
- =counsel-esh-history= - A searchable history of commands typed into Eshell


For more thoughts on Eshell, check out these articles by Pierre Neidhardt:
- https://ambrevar.xyz/emacs-eshell/index.html
- https://ambrevar.xyz/emacs-eshell-versus-shell/index.html

#+begin_src emacs-lisp

  (defun configure-eshell ()
    ;; Save command history when commands are entered
    (add-hook 'eshell-pre-command-hook 'eshell-save-some-history)

    ;; Truncate buffer for performance
    (add-to-list 'eshell-output-filter-functions 'eshell-truncate-buffer)

    (setq eshell-history-size         10000
          eshell-buffer-maximum-lines 10000
          eshell-hist-ignoredups t
          eshell-scroll-to-bottom-on-input t))

  (use-package eshell-git-prompt
    :after eshell)

  (use-package eshell
    :hook (eshell-first-time-mode . configure-eshell)
    :config

    (with-eval-after-load 'esh-opt
      (setq eshell-destroy-buffer-when-process-dies t)
      (setq eshell-visual-commands '("htop" "zsh" "vim")))

    (eshell-git-prompt-use-theme 'powerline))


#+end_src
* File Management
** Dired

Dired is a built-in file manager for Emacs that does some pretty amazing things!  Here are some key bindings you should try out:

*** Key Bindings

**** Navigation

*Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp

  (use-package dired
    :straight nil
    :commands (dired dired-jump)
    :hook
    (dired-mode . dired-hide-details-mode)
    (dired-mode . auto-revert-mode)
    :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-alh --group-directories-first"))
    :config
    (setq dired-dwim-target t)
    (setq dired-recursive-deletes 'always)
    (setq dired-recursive-copies  'always))

  (use-package nerd-icons-dired
    :hook
    (dired-mode . nerd-icons-dired-mode))

  (use-package dired-open
    :commands (dired dired-jump)
    :config
    ;; Doesn't work as expected!
    ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
    (setq dired-open-extensions '(("png" . "feh")
                                  ("mkv" . "mpv"))))

  (use-package dired-hide-dotfiles)

  (defun my-dired-hooks ()
    "Hides extra dired info and binds H to hiding dotfiles."
    (local-set-key (kbd "H") 'dired-hide-dotfiles-mode))
  (add-hook 'dired-mode-hook 'my-dired-hooks)
#+end_src

** Dirvish
[[https://github.com/alexluigit/dirvish#start-of-content][Dirvish]] is a modern and sleek Dired porcelain. Features include peeking, paned previews, images, etc.

#+begin_src emacs-lisp
  (use-package dirvish
    :init
    (dirvish-override-dired-mode)
    :config
    (setq dirvish-mode-line-format
  	'(left (sort symlink) :right (omit printable)))
    (setq dirvish-attributes
  	'(vc-state subgroup-name git-mgs file-size))
    :bind
    (("C-x C-d" . dirvish)
     :map dirvish-mode-map
     ("f" . dirvish-file-info-menu)
     ("y" . dirvish-yank-menu)
     ("N" . dirvish-narrow)
     ("h" . dirvish-history-last)
     ("H" . dirvish-history-jump)
     ("s" . dirvish-quicksort)
     ("TAB" . dirvish-subtree-toggle)
     ("M-t" . dirvish-layout-toggle)))
#+end_src
